LiquiBase: liquibase.change.UpdateDataChange Class Reference
liquibase.change.UpdateDataChange
liquibase.change.UpdateDataChange Class Reference
Detailed Description
Definition at line 15 of file UpdateDataChange.java.
Public Member Functions
UpdateDataChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
List< ColumnConfig > getColumns ()
void setColumns (List< ColumnConfig > columns)
void addColumn (ColumnConfig column)
void removeColumn (ColumnConfig column)
String getWhereClause ()
void setWhereClause (String whereClause)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.UpdateDataChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 67 of file UpdateDataChange.java.
References liquibase.database.sql.UpdateStatement.addNewColumnValue(), liquibase.change.UpdateDataChange.getSchemaName(), liquibase.change.UpdateDataChange.getTableName(), and liquibase.database.sql.UpdateStatement.setWhereClause().
{
        UpdateStatement statement = new UpdateStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName());
        for (ColumnConfig column : columns) {
            statement.addNewColumnValue(column.getName(), column.getValueObject());
        }
        statement.setWhereClause(whereClause);
        return new SqlStatement[]{
                statement
        };
    }
String liquibase.change.UpdateDataChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 82 of file UpdateDataChange.java.
References liquibase.change.UpdateDataChange.getTableName().
{
        return "Data updated in " + getTableName();
    }
Element liquibase.change.UpdateDataChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 86 of file UpdateDataChange.java.
References liquibase.change.UpdateDataChange.getColumns(), liquibase.change.UpdateDataChange.getSchemaName(), liquibase.change.UpdateDataChange.getTableName(), and liquibase.change.UpdateDataChange.getWhereClause().
{
        Element node = currentChangeLogFileDOM.createElement("update");
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        for (ColumnConfig col : getColumns()) {
            Element subNode = col.createNode(currentChangeLogFileDOM);
            node.appendChild(subNode);
        }
        if (StringUtils.trimToNull(getWhereClause()) != null) {
            Element whereClause = currentChangeLogFileDOM.createElement("where");
            whereClause.appendChild(currentChangeLogFileDOM.createTextNode(getWhereClause()));
            node.appendChild(whereClause);
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/UpdateDataChange.java