LiquiBase: liquibase.database.OracleDatabase Class Reference
liquibase.database.OracleDatabase
liquibase.database.OracleDatabase Class Reference
Detailed Description
Encapsulates Oracle database support.
Definition at line 15 of file OracleDatabase.java.
Public Member Functions
void setConnection (Connection conn)
String getProductName ()
Returns the full database product name.
String getTypeName ()
Returns an all-lower-case short name of the product.
boolean supportsInitiallyDeferrableColumns ()
Returns whether this database support initially deferrable columns.
boolean supportsSequences ()
Does the database type support sequence.
String getBooleanType ()
Returns the actual database-specific data type to use a "boolean" column.
String getCurrencyType ()
Returns the actual database-specific data type to use a "currency" column.
String getUUIDType ()
Returns the actual database-specific data type to use a "UUID" column.
String getClobType ()
Returns the actual database-specific data type to use a "CLOB" column.
String getBlobType ()
Returns the actual database-specific data type to use a "BLOB" column.
String getDateTimeType ()
Returns the actual database-specific data type to use a "datetime" column.
String getDateType ()
Returns the actual database-specific data type to use a "date" (no time information) column.
String getTimeType ()
Returns the actual database-specific data type to use a "time" column.
boolean isCorrectDatabaseImplementation (Connection conn) throws JDBCException
Is this AbstractDatabase subclass the correct one to use for the given connection.
String getDefaultDriver (String url)
If this database understands the given url, return the default driver class name.
String getCurrentDateTimeFunction ()
Returns database-specific function for generating the current date/time.
String getTrueBooleanValue ()
The database-specific value to use for "true" "boolean" columns.
String getFalseBooleanValue ()
The database-specific value to use for "false" "boolean" columns.
String getDateLiteral (String isoDate)
Return an Oracle date literal with the same value as a string formatted using ISO 8601.
SqlStatement getSelectChangeLogLockSQL () throws JDBCException
SqlStatement createFindSequencesSQL (String schema) throws JDBCException
boolean isSystemTable (String catalogName, String schemaName, String tableName)
boolean shouldQuoteValue (String value)
boolean supportsTablespaces ()
SqlStatement getViewDefinitionSql (String schemaName, String name) throws JDBCException
boolean supportsAutoIncrement ()
Object convertDatabaseValueToJavaObject (Object defaultValue, int dataType, int columnSize, int decimalDigits) throws ParseException
String getColumnType (String columnType, Boolean autoIncrement)
Returns the database-specific datatype for the given column configuration.
Static Public Attributes
static final String PRODUCT_NAME = "oracle"
Protected Member Functions
String getDefaultDatabaseSchemaName () throws JDBCException
Member Function Documentation
String liquibase.database.OracleDatabase.getProductName ()
Returns the full database product name.
May be different than what the JDBC connection reports (getDatabaseProductName())
Implements liquibase.database.Database.
Definition at line 30 of file OracleDatabase.java.
{
        return "Oracle";
    }
String liquibase.database.OracleDatabase.getTypeName ()
Returns an all-lower-case short name of the product.
Used for end-user selecting of database type such as the DBMS precondition.
Implements liquibase.database.Database.
Definition at line 34 of file OracleDatabase.java.
{
        return "oracle";
    }
String liquibase.database.OracleDatabase.getDefaultDriver (String url)
If this database understands the given url, return the default driver class name.
Otherwise return null.
Implements liquibase.database.Database.
Definition at line 83 of file OracleDatabase.java.
{
        if (url.startsWith("jdbc:oracle")) {
            return "oracle.jdbc.OracleDriver";
        }
        return null;
    }
String liquibase.database.OracleDatabase.getDateLiteral (String isoDate)
Return an Oracle date literal with the same value as a string formatted using ISO 8601.
Convert an ISO8601 date string to one of the following results: to_date('1995-05-23', 'YYYY-MM-DD') to_date('1995-05-23 09:23:59', 'YYYY-MM-DD HH24:MI:SS')
Implementation restriction: Currently, only the following subsets of ISO8601 are supported: YYYY-MM-DD YYYY-MM-DDThh:mm:ss
Reimplemented from liquibase.database.AbstractDatabase.
Definition at line 119 of file OracleDatabase.java.
References liquibase.database.AbstractDatabase.isDateOnly(), liquibase.database.AbstractDatabase.isDateTime(), and liquibase.database.AbstractDatabase.isTimeOnly().
{
        String normalLiteral = super.getDateLiteral(isoDate);
        if (isDateOnly(isoDate)) {
            StringBuffer val = new StringBuffer();
            val.append("to_date(");
            val.append(normalLiteral);
            val.append(", 'YYYY-MM-DD')");
            return val.toString();
        } else if (isTimeOnly(isoDate)) {
            StringBuffer val = new StringBuffer();
            val.append("to_date(");
            val.append(normalLiteral);
            val.append(", 'HH24:MI:SS')");
            return val.toString();
        } else if (isDateTime(isoDate)) {
            normalLiteral = normalLiteral.substring(0, normalLiteral.lastIndexOf('.'))+"'";
            StringBuffer val = new StringBuffer(26);
            val.append("to_date(");
            val.append(normalLiteral);
            val.append(", 'YYYY-MM-DD HH24:MI:SS')");
            return val.toString();
        } else {
            return "UNSUPPORTED:" + isoDate;
        }
    }
String liquibase.database.OracleDatabase.getColumnType (String columnType, Boolean autoIncrement)
Returns the database-specific datatype for the given column configuration.
This method will convert some generic column types (e.g. boolean, currency) to the correct type for the current database.
Reimplemented from liquibase.database.AbstractDatabase.
Definition at line 224 of file OracleDatabase.java.
{
        String s = super.getColumnType(columnType, autoIncrement);
        return s.replaceAll("VARCHAR2", "VARCHAR");
    }
The documentation for this class was generated from the following file:
java/liquibase/database/OracleDatabase.java