LiquiBase: liquibase.change.AddDefaultValueChange Class Reference
liquibase.change.AddDefaultValueChange
liquibase.change.AddDefaultValueChange Class Reference
Detailed Description
Sets a new default value to an existing column.
Definition at line 23 of file AddDefaultValueChange.java.
Public Member Functions
AddDefaultValueChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getColumnName ()
void setColumnName (String columnName)
String getDefaultValue ()
void setDefaultValue (String defaultValue)
String getDefaultValueNumeric ()
void setDefaultValueNumeric (String defaultValueNumeric)
String getDefaultValueDate ()
void setDefaultValueDate (String defaultValueDate)
Boolean getDefaultValueBoolean ()
void setDefaultValueBoolean (Boolean defaultValueBoolean)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.AddDefaultValueChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 95 of file AddDefaultValueChange.java.
References liquibase.change.AddDefaultValueChange.getColumnName(), liquibase.change.AddDefaultValueChange.getDefaultValue(), liquibase.change.AddDefaultValueChange.getDefaultValueBoolean(), liquibase.change.AddDefaultValueChange.getDefaultValueDate(), liquibase.change.AddDefaultValueChange.getDefaultValueNumeric(), liquibase.change.AddDefaultValueChange.getSchemaName(), and liquibase.change.AddDefaultValueChange.getTableName().
{
        Object defaultValue = null;
        try {
            if (getDefaultValue() != null) {
                defaultValue = getDefaultValue();
            } else if (getDefaultValueBoolean() != null) {
                defaultValue = Boolean.valueOf(getDefaultValueBoolean());
            } else if (getDefaultValueNumeric() != null) {
                defaultValue = NumberFormat.getInstance().parse(getDefaultValueNumeric());
            } else if (getDefaultValueDate() != null) {
                defaultValue = new ISODateFormat().parse(getDefaultValueDate());
            }
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
        return new SqlStatement[] {
                new AddDefaultValueStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName(), getColumnName(), defaultValue)
        };
    }
String liquibase.change.AddDefaultValueChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 127 of file AddDefaultValueChange.java.
References liquibase.change.AddDefaultValueChange.getColumnName(), and liquibase.change.AddDefaultValueChange.getTableName().
{
        return "Default value added to " + getTableName() + "." + getColumnName();
    }
Element liquibase.change.AddDefaultValueChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 131 of file AddDefaultValueChange.java.
References liquibase.change.AddDefaultValueChange.getColumnName(), liquibase.change.AddDefaultValueChange.getDefaultValue(), liquibase.change.AddDefaultValueChange.getDefaultValueBoolean(), liquibase.change.AddDefaultValueChange.getDefaultValueDate(), liquibase.change.AddDefaultValueChange.getDefaultValueNumeric(), liquibase.change.AddDefaultValueChange.getSchemaName(), liquibase.change.AddDefaultValueChange.getTableName(), and liquibase.change.AbstractChange.getTagName().
{
        Element node = currentChangeLogFileDOM.createElement(getTagName());
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        node.setAttribute("columnName", getColumnName());
        if (getDefaultValue() != null) {
            node.setAttribute("defaultValue", getDefaultValue());
        }
        if (getDefaultValueNumeric() != null) {
            node.setAttribute("defaultValueNumeric", getDefaultValueNumeric());
        }
        if (getDefaultValueDate() != null) {
            node.setAttribute("defaultValueDate", getDefaultValueDate());
        }
        if (getDefaultValueBoolean() != null) {
            node.setAttribute("defaultValueBoolean", getDefaultValueBoolean().toString());
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AddDefaultValueChange.java