LiquiBase: liquibase.Liquibase Class Reference
liquibase.Liquibase
liquibase.Liquibase Class Reference
Detailed Description
Core LiquiBase facade.
Although there are several ways of executing LiquiBase (Ant, command line, etc.) they are all wrappers around this class.
Definition at line 37 of file Liquibase.java.
Public Member Functions
Liquibase (String changeLogFile, FileOpener fileOpener, Database database)
Database getDatabase ()
FileOpener getFileOpener ()
FileOpener to use for accessing changelog files.
void setCurrentDateTimeFunction (String currentDateTimeFunction)
Use this function to override the current date/time function used to insert dates into the database.
void update (String contexts) throws LiquibaseException
void update (String contexts, Writer output) throws LiquibaseException
void update (int changesToApply, String contexts) throws LiquibaseException
void update (int changesToApply, String contexts, Writer output) throws LiquibaseException
void rollback (int changesToRollback, String contexts, Writer output) throws LiquibaseException
void rollback (int changesToRollback, String contexts) throws LiquibaseException
void rollback (String tagToRollBackTo, String contexts, Writer output) throws LiquibaseException
void rollback (String tagToRollBackTo, String contexts) throws LiquibaseException
void rollback (Date dateToRollBackTo, String contexts, Writer output) throws LiquibaseException
void rollback (Date dateToRollBackTo, String contexts) throws LiquibaseException
void changeLogSync (String contexts, Writer output) throws LiquibaseException
void changeLogSync (String contexts) throws LiquibaseException
void futureRollbackSQL (String contexts, Writer output) throws LiquibaseException
final void dropAll () throws JDBCException, LockException
Drops all database objects owned by the current user.
final void dropAll (String...schemas) throws JDBCException
Drops all database objects owned by the current user.
void tag (String tagString) throws JDBCException
'Tags' the database for future rollback
void checkDatabaseChangeLogTable () throws JDBCException
boolean isSafeToRunMigration () throws JDBCException
Returns true if it is "save" to migrate the database.
DatabaseChangeLogLock[] listLocks () throws JDBCException, IOException, LockException
Display change log lock information.
void reportLocks (PrintStream out) throws LockException, IOException, JDBCException
void forceReleaseLocks () throws LockException, IOException, JDBCException
List< ChangeSet > listUnrunChangeSets (String contexts) throws LiquibaseException
void reportStatus (boolean verbose, String contexts, Writer out) throws LiquibaseException
void clearCheckSums () throws LiquibaseException
Sets checksums to null so they will be repopulated next run.
void generateDocumentation (String outputDirectory) throws LiquibaseException
void validate () throws LiquibaseException
Checks changelogs for bad MD5Sums and preconditions before attempting a migration.
Static Public Attributes
static final String SHOULD_RUN_SYSTEM_PROPERTY = "liquibase.should.run"
Member Function Documentation
void liquibase.Liquibase.setCurrentDateTimeFunction (String currentDateTimeFunction)
Use this function to override the current date/time function used to insert dates into the database.
Especially useful when using an unsupported database.
Definition at line 73 of file Liquibase.java.
Referenced by liquibase.ant.BaseLiquibaseTask.createLiquibase().
{
        if (currentDateTimeFunction != null) {
            this.database.setCurrentDateTimeFunction(currentDateTimeFunction);
        }
    }
boolean liquibase.Liquibase.isSafeToRunMigration () throws JDBCException
Returns true if it is "save" to migrate the database.
Currently, "safe" is defined as running in an output-sql mode or against a database on localhost. It is fine to run LiquiBase against a "non-safe" database, the method is mainly used to determine if the user should be prompted before continuing.
Definition at line 416 of file Liquibase.java.
References liquibase.database.template.JdbcTemplate.executesStatements(), liquibase.database.Database.getConnectionURL(), liquibase.Liquibase.getDatabase(), and liquibase.database.Database.getJdbcTemplate().
Referenced by liquibase.ant.DatabaseUpdateTask.execute().
{
        return !getDatabase().getJdbcTemplate().executesStatements() || getDatabase().getConnectionURL().indexOf("localhost") >= 0;
    }
The documentation for this class was generated from the following file:
java/liquibase/Liquibase.java