LiquiBase: liquibase.change.AddAutoIncrementChange Class Reference
liquibase.change.AddAutoIncrementChange
liquibase.change.AddAutoIncrementChange Class Reference
Detailed Description
Makes an existing column into an auto-increment column.
This change is only valid for databases with auto-increment/identity columns. The current version does not support MS-SQL.
Definition at line 22 of file AddAutoIncrementChange.java.
Public Member Functions
AddAutoIncrementChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getColumnName ()
void setColumnName (String columnName)
String getColumnDataType ()
void setColumnDataType (String columnDataType)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.AddAutoIncrementChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 65 of file AddAutoIncrementChange.java.
References liquibase.change.AddAutoIncrementChange.getColumnDataType(), liquibase.change.AddAutoIncrementChange.getColumnName(), liquibase.change.AddAutoIncrementChange.getSchemaName(), and liquibase.change.AddAutoIncrementChange.getTableName().
{
        String schemaName = getSchemaName() == null?database.getDefaultSchemaName():getSchemaName();
        if (database instanceof PostgresDatabase) {
            String sequenceName = (getTableName()+"_"+getColumnName()+"_seq").toLowerCase();
            return new SqlStatement[]{
                    new CreateSequenceStatement(schemaName, sequenceName),
                    new SetNullableStatement(schemaName, getTableName(), getColumnName(), null, false),
                    new AddDefaultValueStatement(schemaName, getTableName(), getColumnName(), sequenceName),
            };
        } else {
            return new SqlStatement[] { new AddAutoIncrementStatement(schemaName, getTableName(), getColumnName(), getColumnDataType())};
        }
    }
String liquibase.change.AddAutoIncrementChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 79 of file AddAutoIncrementChange.java.
References liquibase.change.AddAutoIncrementChange.getColumnName(), and liquibase.change.AddAutoIncrementChange.getTableName().
{
        return "Auto-increment added to "+getTableName()+"."+getColumnName();
    }
Element liquibase.change.AddAutoIncrementChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 83 of file AddAutoIncrementChange.java.
References liquibase.change.AddAutoIncrementChange.getColumnDataType(), liquibase.change.AddAutoIncrementChange.getColumnName(), liquibase.change.AddAutoIncrementChange.getSchemaName(), and liquibase.change.AddAutoIncrementChange.getTableName().
{
        Element node = currentChangeLogFileDOM.createElement("addAutoIncrement");
        node.setAttribute("tableName", getTableName());
        node.setAttribute("columnName", getColumnName());
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        if (getColumnDataType() != null) {
            node.setAttribute("columnDataType", getColumnDataType());
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AddAutoIncrementChange.java