LiquiBase: liquibase.change.CreateProcedureChange Class Reference
liquibase.change.CreateProcedureChange
liquibase.change.CreateProcedureChange Class Reference
Detailed Description
Definition at line 14 of file CreateProcedureChange.java.
Public Member Functions
CreateProcedureChange ()
String getProcedureBody ()
void setProcedureBody (String procedureBody)
String getComments ()
void setComments (String comments)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.CreateProcedureChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 38 of file CreateProcedureChange.java.
References liquibase.change.CreateProcedureChange.getProcedureBody().
{
        String endDelimiter = ";";
        if (database instanceof OracleDatabase) {
            endDelimiter = "\n/";
        }
        return new SqlStatement[] {
                new RawSqlStatement(getProcedureBody(), endDelimiter),
        };
    }
String liquibase.change.CreateProcedureChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 48 of file CreateProcedureChange.java.
{
        return "Stored procedure created";
    }
Element liquibase.change.CreateProcedureChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 52 of file CreateProcedureChange.java.
References liquibase.change.CreateProcedureChange.getProcedureBody(), and liquibase.change.AbstractChange.getTagName().
{
        Element sqlElement = currentChangeLogFileDOM.createElement(getTagName());
        sqlElement.appendChild(currentChangeLogFileDOM.createTextNode(getProcedureBody()));
        return sqlElement;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/CreateProcedureChange.java