LiquiBase: liquibase.change.DropColumnChange Class Reference
liquibase.change.DropColumnChange
liquibase.change.DropColumnChange Class Reference
Detailed Description
Drops an existing column from a table.
Definition at line 20 of file DropColumnChange.java.
Public Member Functions
DropColumnChange ()
String getColumnName ()
void setColumnName (String columnName)
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.DropColumnChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 55 of file DropColumnChange.java.
References liquibase.change.DropColumnChange.getColumnName(), liquibase.change.DropColumnChange.getSchemaName(), and liquibase.change.DropColumnChange.getTableName().
Referenced by liquibase.change.MergeColumnChange.generateStatements().
{
        List<SqlStatement> statements = new ArrayList<SqlStatement>();
        String schemaName = getSchemaName() == null?database.getDefaultSchemaName():getSchemaName();
        statements.add(new DropColumnStatement(schemaName, getTableName(), getColumnName()));
        if (database instanceof DB2Database) {
            statements.add(new ReorganizeTableStatement(schemaName, getTableName()));
        }
        return statements.toArray(new SqlStatement[statements.size()]);
    }
String liquibase.change.DropColumnChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 66 of file DropColumnChange.java.
References liquibase.change.DropColumnChange.getColumnName(), and liquibase.change.DropColumnChange.getTableName().
{
        return "Column " + getTableName() + "." + getColumnName() + " dropped";
    }
Element liquibase.change.DropColumnChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 70 of file DropColumnChange.java.
References liquibase.change.DropColumnChange.getColumnName(), liquibase.change.DropColumnChange.getSchemaName(), and liquibase.change.DropColumnChange.getTableName().
{
        Element element = currentChangeLogFileDOM.createElement("dropColumn");
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("tableName", getTableName());
        element.setAttribute("columnName", getColumnName());
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DropColumnChange.java