LiquiBase: liquibase.change.CreateIndexChange Class Reference
liquibase.change.CreateIndexChange
liquibase.change.CreateIndexChange Class Reference
Detailed Description
Creates an index on an existing column.
Definition at line 18 of file CreateIndexChange.java.
Public Member Functions
CreateIndexChange ()
String getIndexName ()
void setIndexName (String indexName)
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
List< ColumnConfig > getColumns ()
void setColumns (List< ColumnConfig > columns)
void addColumn (ColumnConfig column)
String getTablespace ()
void setTablespace (String tablespace)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.CreateIndexChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 77 of file CreateIndexChange.java.
References liquibase.change.CreateIndexChange.getColumns(), liquibase.change.CreateIndexChange.getIndexName(), liquibase.change.CreateIndexChange.getSchemaName(), liquibase.change.CreateIndexChange.getTableName(), liquibase.change.CreateIndexChange.getTablespace(), and liquibase.change.CreateIndexChange.setTablespace().
{
        List<String> columns = new ArrayList<String>();
        for (ColumnConfig column : getColumns()) {
            columns.add(column.getName());
        }
        return new SqlStatement []{
                new CreateIndexStatement(getIndexName(), getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName(), columns.toArray(new String[getColumns().size()])).setTablespace(getTablespace())
        };
    }
String liquibase.change.CreateIndexChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 99 of file CreateIndexChange.java.
References liquibase.change.CreateIndexChange.getIndexName().
{
        return "Index " + getIndexName() + " created";
    }
Element liquibase.change.CreateIndexChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 103 of file CreateIndexChange.java.
References liquibase.change.CreateIndexChange.getColumns(), liquibase.change.CreateIndexChange.getIndexName(), liquibase.change.CreateIndexChange.getSchemaName(), and liquibase.change.CreateIndexChange.getTableName().
{
        Element element = currentChangeLogFileDOM.createElement("createIndex");
        element.setAttribute("indexName", getIndexName());
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("tableName", getTableName());
        for (ColumnConfig column : getColumns()) {
            Element columnElement = currentChangeLogFileDOM.createElement("column");
            columnElement.setAttribute("name", column.getName());
            element.appendChild(columnElement);
        }
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/CreateIndexChange.java