LiquiBase: liquibase.change.AddColumnChange Class Reference
liquibase.change.AddColumnChange
liquibase.change.AddColumnChange Class Reference
Detailed Description
Adds a column to an existing table.
Definition at line 19 of file AddColumnChange.java.
Public Member Functions
AddColumnChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
List< ColumnConfig > getColumns ()
ColumnConfig getLastColumn ()
void addColumn (ColumnConfig column)
void removeColumn (ColumnConfig column)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.AddColumnChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 62 of file AddColumnChange.java.
References liquibase.database.sql.UpdateStatement.addNewColumnValue(), liquibase.change.AddPrimaryKeyChange.generateStatements(), liquibase.change.AddColumnChange.getSchemaName(), liquibase.change.AddColumnChange.getTableName(), liquibase.change.AddPrimaryKeyChange.setColumnNames(), liquibase.change.AddPrimaryKeyChange.setSchemaName(), and liquibase.change.AddPrimaryKeyChange.setTableName().
{
        List<SqlStatement> sql = new ArrayList<SqlStatement>();
        String schemaName = getSchemaName() == null?database.getDefaultSchemaName():getSchemaName();
        for (ColumnConfig aColumn : columns) {
            Set<ColumnConstraint> constraints = new HashSet<ColumnConstraint>();
            if (aColumn.getConstraints() != null) {
                if (aColumn.getConstraints().isNullable() != null && !aColumn.getConstraints().isNullable()) {
                    constraints.add(new NotNullConstraint());
                }
            }
            AddColumnStatement addColumnStatement = new AddColumnStatement(schemaName,
                    getTableName(),
                    aColumn.getName(),
                    aColumn.getType(),
                    aColumn.getDefaultValueObject(),
                    constraints.toArray(new ColumnConstraint[constraints.size()]));
            sql.add(addColumnStatement);
            if (aColumn.getValueObject() != null) {
                UpdateStatement updateStatement = new UpdateStatement(schemaName, getTableName());
                updateStatement.addNewColumnValue(aColumn.getName(), aColumn.getValueObject());
                sql.add(updateStatement);
            }
        }
        for (ColumnConfig aColumn : columns) {
            if (aColumn.getConstraints() != null) {
                if (aColumn.getConstraints().isPrimaryKey() != null && aColumn.getConstraints().isPrimaryKey()) {
                    AddPrimaryKeyChange change = new AddPrimaryKeyChange();
                    change.setSchemaName(schemaName);
                    change.setTableName(getTableName());
                    change.setColumnNames(aColumn.getName());
                    sql.addAll(Arrays.asList(change.generateStatements(database)));
                }
            }
        }
        if (database instanceof DB2Database) {
            sql.add(new ReorganizeTableStatement(schemaName, getTableName()));
        }
        return sql.toArray(new SqlStatement[sql.size()]);
    }
String liquibase.change.AddColumnChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 133 of file AddColumnChange.java.
{
        List<String> names = new ArrayList<String>(columns.size());
        for (ColumnConfig col : columns) {
            names.add(col.getName() + "(" + col.getType() + ")");
        }
        return "Columns " + StringUtils.join(names, ",") + " added to " + tableName;
    }
Element liquibase.change.AddColumnChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 142 of file AddColumnChange.java.
References liquibase.change.AddColumnChange.getColumns(), liquibase.change.AddColumnChange.getSchemaName(), and liquibase.change.AddColumnChange.getTableName().
{
        Element node = currentChangeLogFileDOM.createElement("addColumn");
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        for (ColumnConfig col : getColumns()) {
            Element subNode = col.createNode(currentChangeLogFileDOM);
            node.appendChild(subNode);
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AddColumnChange.java