LiquiBase: liquibase.change.AlterSequenceChange Class Reference
liquibase.change.AlterSequenceChange
liquibase.change.AlterSequenceChange Class Reference
Detailed Description
Modifies properties of an existing sequence.
Definition at line 19 of file AlterSequenceChange.java.
Public Member Functions
AlterSequenceChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getSequenceName ()
void setSequenceName (String sequenceName)
Integer getIncrementBy ()
void setIncrementBy (Integer incrementBy)
Integer getMaxValue ()
void setMaxValue (Integer maxValue)
Integer getMinValue ()
void setMinValue (Integer minValue)
Boolean isOrdered ()
void setOrdered (Boolean ordered)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.AlterSequenceChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 82 of file AlterSequenceChange.java.
References liquibase.change.AlterSequenceChange.getIncrementBy(), liquibase.change.AlterSequenceChange.getMaxValue(), liquibase.change.AlterSequenceChange.getMinValue(), liquibase.change.AlterSequenceChange.getSchemaName(), liquibase.change.AlterSequenceChange.getSequenceName(), liquibase.change.AlterSequenceChange.isOrdered(), liquibase.change.AlterSequenceChange.setIncrementBy(), liquibase.change.AlterSequenceChange.setMaxValue(), liquibase.change.AlterSequenceChange.setMinValue(), and liquibase.change.AlterSequenceChange.setOrdered().
{
        if (!database.supportsSequences()) {
            throw new UnsupportedChangeException("Sequences do not exist in "+database.getProductName());
        }
        return new SqlStatement[] {
                new AlterSequenceStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getSequenceName())
                .setIncrementBy(getIncrementBy())
                .setMaxValue(getMaxValue())
                .setMinValue(getMinValue())
                .setOrdered(isOrdered())
        };
    }
String liquibase.change.AlterSequenceChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 96 of file AlterSequenceChange.java.
References liquibase.change.AlterSequenceChange.getSequenceName().
{
        return "Sequence " + getSequenceName() + " altered";
    }
Element liquibase.change.AlterSequenceChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 100 of file AlterSequenceChange.java.
References liquibase.change.AlterSequenceChange.getIncrementBy(), liquibase.change.AlterSequenceChange.getMaxValue(), liquibase.change.AlterSequenceChange.getMinValue(), liquibase.change.AlterSequenceChange.getSchemaName(), liquibase.change.AlterSequenceChange.getSequenceName(), and liquibase.change.AlterSequenceChange.isOrdered().
{
        Element node = currentChangeLogFileDOM.createElement("alterSequence");
        node.setAttribute("sequenceName", getSequenceName());
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        if (getMinValue() != null) {
            node.setAttribute("minValue", getMinValue().toString());
        }
        if (getMaxValue() != null) {
            node.setAttribute("maxValue", getMaxValue().toString());
        }
        if (getIncrementBy() != null) {
            node.setAttribute("incrementBy", getIncrementBy().toString());
        }
        if (isOrdered() != null) {
            node.setAttribute("ordered", isOrdered().toString());
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AlterSequenceChange.java