LiquiBase: liquibase.change.AddLookupTableChange Class Reference
liquibase.change.AddLookupTableChange
liquibase.change.AddLookupTableChange Class Reference
Detailed Description
Extracts data from an existing column to create a lookup table.
A foreign key is created between the old column and the new lookup table.
Definition at line 21 of file AddLookupTableChange.java.
Public Member Functions
AddLookupTableChange ()
String getExistingTableSchemaName ()
void setExistingTableSchemaName (String existingTableSchemaName)
String getExistingTableName ()
void setExistingTableName (String existingTableName)
String getExistingColumnName ()
void setExistingColumnName (String existingColumnName)
String getNewTableSchemaName ()
void setNewTableSchemaName (String newTableSchemaName)
String getNewTableName ()
void setNewTableName (String newTableName)
String getNewColumnName ()
void setNewColumnName (String newColumnName)
String getNewColumnDataType ()
void setNewColumnDataType (String newColumnDataType)
String getConstraintName ()
String getFinalConstraintName ()
void setConstraintName (String constraintName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.AddLookupTableChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 126 of file AddLookupTableChange.java.
References liquibase.change.AddForeignKeyConstraintChange.generateStatements(), liquibase.change.AddPrimaryKeyChange.generateStatements(), liquibase.change.AddNotNullConstraintChange.generateStatements(), liquibase.change.AddLookupTableChange.getExistingColumnName(), liquibase.change.AddLookupTableChange.getExistingTableName(), liquibase.change.AddLookupTableChange.getExistingTableSchemaName(), liquibase.change.AddLookupTableChange.getFinalConstraintName(), liquibase.change.AddLookupTableChange.getNewColumnDataType(), liquibase.change.AddLookupTableChange.getNewColumnName(), liquibase.change.AddLookupTableChange.getNewTableName(), liquibase.change.AddLookupTableChange.getNewTableSchemaName(), liquibase.change.AddForeignKeyConstraintChange.setBaseColumnNames(), liquibase.change.AddForeignKeyConstraintChange.setBaseTableName(), liquibase.change.AddForeignKeyConstraintChange.setBaseTableSchemaName(), liquibase.change.AddNotNullConstraintChange.setColumnDataType(), liquibase.change.AddNotNullConstraintChange.setColumnName(), liquibase.change.AddPrimaryKeyChange.setColumnNames(), liquibase.change.AddForeignKeyConstraintChange.setConstraintName(), liquibase.change.AddForeignKeyConstraintChange.setReferencedColumnNames(), liquibase.change.AddForeignKeyConstraintChange.setReferencedTableName(), liquibase.change.AddForeignKeyConstraintChange.setReferencedTableSchemaName(), liquibase.change.AddPrimaryKeyChange.setSchemaName(), liquibase.change.AddNotNullConstraintChange.setSchemaName(), liquibase.change.AddPrimaryKeyChange.setTableName(), and liquibase.change.AddNotNullConstraintChange.setTableName().
{
        if (database instanceof DerbyDatabase) {
            throw new UnsupportedChangeException("Add Lookup Table currently not supported in Derby");
        } else if (database instanceof HsqlDatabase) {
            throw new UnsupportedChangeException("Add Lookup Table currently not supported in HSQLDB");
        } else if (database instanceof CacheDatabase) {
            throw new UnsupportedChangeException("Add Lookup Table not currently supported for Cache");
        } else if (database instanceof FirebirdDatabase) {
            throw new UnsupportedChangeException("Add Lookup Table not currently supported for Firebird");
        }
        List<SqlStatement> statements = new ArrayList<SqlStatement>();
        String newTableSchemaName = getNewTableSchemaName() == null?database.getDefaultSchemaName():getNewTableSchemaName();
        String existingTableSchemaName = getExistingTableSchemaName() == null?database.getDefaultSchemaName():getExistingTableSchemaName();
        SqlStatement[] createTablesSQL = {new RawSqlStatement("CREATE TABLE " + database.escapeTableName(newTableSchemaName, getNewTableName()) + " AS SELECT DISTINCT " + getExistingColumnName() + " AS " + getNewColumnName() + " FROM " + database.escapeTableName(existingTableSchemaName, getExistingTableName()) + " WHERE " + getExistingColumnName() + " IS NOT NULL")};
        if (database instanceof MSSQLDatabase) {
            createTablesSQL = new SqlStatement[]{new RawSqlStatement("SELECT DISTINCT " + getExistingColumnName() + " AS " + getNewColumnName() + " INTO " + database.escapeTableName(newTableSchemaName, getNewTableName()) + " FROM " + database.escapeTableName(existingTableSchemaName, getExistingTableName()) + " WHERE " + getExistingColumnName() + " IS NOT NULL"),};
        } else if (database instanceof DB2Database) {
            createTablesSQL = new SqlStatement[]{
                    new RawSqlStatement("CREATE TABLE " + database.escapeTableName(newTableSchemaName, getNewTableName()) + " AS (SELECT " + getExistingColumnName() + " AS " + getNewColumnName() + " FROM " + database.escapeTableName(existingTableSchemaName, getExistingTableName()) + ") WITH NO DATA"),
                    new RawSqlStatement("INSERT INTO " + database.escapeTableName(newTableSchemaName, getNewTableName()) + " SELECT DISTINCT " + getExistingColumnName() + " FROM " + database.escapeTableName(existingTableSchemaName, getExistingTableName()) + " WHERE " + getExistingColumnName() + " IS NOT NULL"),
            };
        }
        statements.addAll(Arrays.asList(createTablesSQL));
        if (!(database instanceof OracleDatabase)) {
            AddNotNullConstraintChange addNotNullChange = new AddNotNullConstraintChange();
            addNotNullChange.setSchemaName(newTableSchemaName);
            addNotNullChange.setTableName(getNewTableName());
            addNotNullChange.setColumnName(getNewColumnName());
            addNotNullChange.setColumnDataType(getNewColumnDataType());
            statements.addAll(Arrays.asList(addNotNullChange.generateStatements(database)));
        }
        if (database instanceof DB2Database) {
            statements.add(new ReorganizeTableStatement(newTableSchemaName, getNewTableName()));
        }
        AddPrimaryKeyChange addPKChange = new AddPrimaryKeyChange();
        addPKChange.setSchemaName(newTableSchemaName);
        addPKChange.setTableName(getNewTableName());
        addPKChange.setColumnNames(getNewColumnName());
        statements.addAll(Arrays.asList(addPKChange.generateStatements(database)));
        if (database instanceof DB2Database) {
            statements.add(new ReorganizeTableStatement(newTableSchemaName, getNewTableName()));
        }
        AddForeignKeyConstraintChange addFKChange = new AddForeignKeyConstraintChange();
        addFKChange.setBaseTableSchemaName(existingTableSchemaName);
        addFKChange.setBaseTableName(getExistingTableName());
        addFKChange.setBaseColumnNames(getExistingColumnName());
        addFKChange.setReferencedTableSchemaName(newTableSchemaName);
        addFKChange.setReferencedTableName(getNewTableName());
        addFKChange.setReferencedColumnNames(getNewColumnName());
        addFKChange.setConstraintName(getFinalConstraintName());
        statements.addAll(Arrays.asList(addFKChange.generateStatements(database)));
        return statements.toArray(new SqlStatement[statements.size()]);
    }
String liquibase.change.AddLookupTableChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 191 of file AddLookupTableChange.java.
References liquibase.change.AddLookupTableChange.getExistingColumnName(), and liquibase.change.AddLookupTableChange.getExistingTableName().
{
        return "Lookup table added for "+getExistingTableName()+"."+getExistingColumnName();
    }
Element liquibase.change.AddLookupTableChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 195 of file AddLookupTableChange.java.
References liquibase.change.AddLookupTableChange.getConstraintName(), liquibase.change.AddLookupTableChange.getExistingColumnName(), liquibase.change.AddLookupTableChange.getExistingTableName(), liquibase.change.AddLookupTableChange.getExistingTableSchemaName(), liquibase.change.AddLookupTableChange.getNewColumnName(), liquibase.change.AddLookupTableChange.getNewTableName(), liquibase.change.AddLookupTableChange.getNewTableSchemaName(), and liquibase.change.AbstractChange.getTagName().
{
        Element node = currentChangeLogFileDOM.createElement(getTagName());
        if (getExistingTableSchemaName() != null) {
            node.setAttribute("newTableSchemaName", getExistingTableSchemaName());
        }
        node.setAttribute("existingTableName", getExistingTableName());
        node.setAttribute("existingColumnName", getExistingColumnName());
        if (getNewTableSchemaName() != null) {
            node.setAttribute("newTableSchemaName", getNewTableSchemaName());
        }
        node.setAttribute("newTableName", getNewTableName());
        node.setAttribute("newColumnName", getNewColumnName());
        node.setAttribute("constraintName", getConstraintName());
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AddLookupTableChange.java