LiquiBase: liquibase.change.AddForeignKeyConstraintChange Class Reference
liquibase.change.AddForeignKeyConstraintChange
liquibase.change.AddForeignKeyConstraintChange Class Reference
Detailed Description
Adds a foreign key constraint to an existing column.
Definition at line 20 of file AddForeignKeyConstraintChange.java.
Public Member Functions
AddForeignKeyConstraintChange ()
String getBaseTableSchemaName ()
void setBaseTableSchemaName (String baseTableSchemaName)
String getBaseTableName ()
void setBaseTableName (String baseTableName)
String getBaseColumnNames ()
void setBaseColumnNames (String baseColumnNames)
String getReferencedTableSchemaName ()
void setReferencedTableSchemaName (String referencedTableSchemaName)
String getReferencedTableName ()
void setReferencedTableName (String referencedTableName)
String getReferencedColumnNames ()
void setReferencedColumnNames (String referencedColumnNames)
String getConstraintName ()
void setConstraintName (String constraintName)
Boolean getDeferrable ()
void setDeferrable (Boolean deferrable)
Boolean getInitiallyDeferred ()
void setInitiallyDeferred (Boolean initiallyDeferred)
Boolean getDeleteCascade ()
void setDeleteCascade (Boolean deleteCascade)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.AddForeignKeyConstraintChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 121 of file AddForeignKeyConstraintChange.java.
References liquibase.change.AddForeignKeyConstraintChange.getBaseColumnNames(), liquibase.change.AddForeignKeyConstraintChange.getBaseTableName(), liquibase.change.AddForeignKeyConstraintChange.getBaseTableSchemaName(), liquibase.change.AddForeignKeyConstraintChange.getConstraintName(), liquibase.change.AddForeignKeyConstraintChange.getDeferrable(), liquibase.change.AddForeignKeyConstraintChange.getDeleteCascade(), liquibase.change.AddForeignKeyConstraintChange.getInitiallyDeferred(), liquibase.change.AddForeignKeyConstraintChange.getReferencedColumnNames(), liquibase.change.AddForeignKeyConstraintChange.getReferencedTableName(), liquibase.change.AddForeignKeyConstraintChange.getReferencedTableSchemaName(), and liquibase.change.AddForeignKeyConstraintChange.setDeferrable().
Referenced by liquibase.change.AddLookupTableChange.generateStatements().
{
        boolean deferrable = false;
        if (getDeferrable() != null) {
            deferrable = getDeferrable();
        }
        boolean initiallyDeferred = false;
        if (getInitiallyDeferred() != null) {
            initiallyDeferred = getInitiallyDeferred();
        }
        boolean deleteCascade = false;
        if (getDeleteCascade() != null) {
            deleteCascade = getDeleteCascade();
        }
        return new SqlStatement[]{
                new AddForeignKeyConstraintStatement(getConstraintName(),
                        getBaseTableSchemaName() == null?database.getDefaultSchemaName():getBaseTableSchemaName(),
                        getBaseTableName(),
                        getBaseColumnNames(),
                        getReferencedTableSchemaName() == null?database.getDefaultSchemaName():getReferencedTableSchemaName(),
                        getReferencedTableName(),
                        getReferencedColumnNames())
                .setDeferrable(deferrable)
                .setInitiallyDeferred(initiallyDeferred)
                .setDeleteCascade(deleteCascade)
        };
    }
String liquibase.change.AddForeignKeyConstraintChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 162 of file AddForeignKeyConstraintChange.java.
References liquibase.change.AddForeignKeyConstraintChange.getBaseColumnNames(), and liquibase.change.AddForeignKeyConstraintChange.getBaseTableName().
{
        return "Foreign key contraint added to " + getBaseTableName() + " (" + getBaseColumnNames() + ")";
    }
Element liquibase.change.AddForeignKeyConstraintChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 166 of file AddForeignKeyConstraintChange.java.
References liquibase.change.AddForeignKeyConstraintChange.getBaseColumnNames(), liquibase.change.AddForeignKeyConstraintChange.getBaseTableName(), liquibase.change.AddForeignKeyConstraintChange.getBaseTableSchemaName(), liquibase.change.AddForeignKeyConstraintChange.getConstraintName(), liquibase.change.AddForeignKeyConstraintChange.getDeferrable(), liquibase.change.AddForeignKeyConstraintChange.getDeleteCascade(), liquibase.change.AddForeignKeyConstraintChange.getInitiallyDeferred(), liquibase.change.AddForeignKeyConstraintChange.getReferencedColumnNames(), liquibase.change.AddForeignKeyConstraintChange.getReferencedTableName(), liquibase.change.AddForeignKeyConstraintChange.getReferencedTableSchemaName(), and liquibase.change.AbstractChange.getTagName().
{
        Element node = currentChangeLogFileDOM.createElement(getTagName());
        if (getBaseTableSchemaName() != null) {
            node.setAttribute("baseTableSchemaName", getBaseTableSchemaName());
        }
        node.setAttribute("baseTableName", getBaseTableName());
        node.setAttribute("baseColumnNames", getBaseColumnNames());
        node.setAttribute("constraintName", getConstraintName());
        if (getReferencedTableSchemaName() != null) {
            node.setAttribute("referencedTableSchemaName", getReferencedTableSchemaName());
        }
        node.setAttribute("referencedTableName", getReferencedTableName());
        node.setAttribute("referencedColumnNames", getReferencedColumnNames());
        if (getDeferrable() != null) {
            node.setAttribute("deferrable", getDeferrable().toString());
        }
        if (getInitiallyDeferred() != null) {
            node.setAttribute("initiallyDeferred", getInitiallyDeferred().toString());
        }
        if (getDeleteCascade() != null) {
            node.setAttribute("deleteCascade", getDeleteCascade().toString());
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AddForeignKeyConstraintChange.java