LiquiBase: liquibase.util.StreamUtil Class Reference
liquibase.util.StreamUtil
liquibase.util.StreamUtil Class Reference
Detailed Description
Utilities for working with streams.
Definition at line 8 of file StreamUtil.java.
Static Public Member Functions
static String getLineSeparator ()
static String getStreamContents (InputStream ins) throws IOException
Reads a stream until the end of file into a String and uses the machines default encoding to convert to characters the bytes from the Stream.
static String getStreamContents (InputStream ins, String charsetName) throws IOException
Reads a stream until the end of file into a String and uses the machines default encoding to convert to characters the bytes from the Stream.
static String getReaderContents (Reader reader) throws IOException
Reads all the characters into a String.
static void copy (InputStream inputStream, OutputStream outputStream) throws IOException
Member Function Documentation
static String liquibase.util.StreamUtil.getStreamContents (InputStream ins) throws IOException [static]
Reads a stream until the end of file into a String and uses the machines default encoding to convert to characters the bytes from the Stream.
Parameters:
ins The InputStream to read.
Returns:
The contents of the input stream as a String
Exceptions:
IOException If there is an error reading the stream.
Definition at line 22 of file StreamUtil.java.
References liquibase.util.StreamUtil.getReaderContents().
{
        InputStreamReader reader = new InputStreamReader(ins);
        return getReaderContents(reader);
    }
static String liquibase.util.StreamUtil.getStreamContents (InputStream ins, String charsetName) throws IOException [static]
Reads a stream until the end of file into a String and uses the machines default encoding to convert to characters the bytes from the Stream.
Parameters:
ins The InputStream to read.
charsetName The name of a supported charset
Returns:
The contents of the input stream as a String
Exceptions:
IOException If there is an error reading the stream.
Definition at line 37 of file StreamUtil.java.
References liquibase.util.StreamUtil.getReaderContents().
{
        InputStreamReader reader = (charsetName != null) ? new InputStreamReader(ins, charsetName) : new InputStreamReader(ins);
        return getReaderContents(reader);
    }
static String liquibase.util.StreamUtil.getReaderContents (Reader reader) throws IOException [static]
Reads all the characters into a String.
Parameters:
reader The Reader to read.
Returns:
The contents of the input stream as a String
Exceptions:
IOException If there is an error reading the stream.
Definition at line 50 of file StreamUtil.java.
Referenced by liquibase.util.StreamUtil.getStreamContents().
{
        try {
            StringBuffer result = new StringBuffer();
            char[] buffer = new char[2048];
            int read;
            while ((read = reader.read(buffer)) > -1) {
                result.append(buffer, 0, read);
            }
            return result.toString();
        } finally {
            try {
                reader.close();
            } catch (IOException ioe) {//NOPMD
                // can safely ignore
            }
        }
    }
The documentation for this class was generated from the following file:
java/liquibase/util/StreamUtil.java