LiquiBase: liquibase.change.AbstractChange Class Reference
liquibase.change.AbstractChange Class Reference
Detailed Description
Standard superclass for Changes to implement.
This is a skeletal implementation, as defined in Effective Java#16.
See also:
Change
Definition at line 30 of file AbstractChange.java.
Public Member Functions
String getChangeName ()
String getTagName ()
void executeStatements (Database database) throws JDBCException, UnsupportedChangeException
void saveStatements (Database database, Writer writer) throws IOException, UnsupportedChangeException, StatementNotSupportedOnDatabaseException
void executeRollbackStatements (Database database) throws JDBCException, UnsupportedChangeException, RollbackImpossibleException
void saveRollbackStatement (Database database, Writer writer) throws IOException, UnsupportedChangeException, RollbackImpossibleException, StatementNotSupportedOnDatabaseException
SqlStatement[] generateRollbackStatements (Database database) throws UnsupportedChangeException, RollbackImpossibleException
boolean canRollBack ()
String getMD5Sum ()
void setFileOpener (FileOpener fileOpener)
Default implementation that stores the file opener provided when the Change was created.
FileOpener getFileOpener ()
Returns the FileOpen as provided by the creating ChangeLog.
void setUp () throws SetupException
Most Changes don't need to do any setup.
Protected Member Functions
AbstractChange (String tagName, String changeName)
Constructor with tag name and name.
Constructor & Destructor Documentation
liquibase.change.AbstractChange.AbstractChange (String tagName, String changeName) [protected]
Constructor with tag name and name.
Parameters:
tagName the tag name for this change
changeName the name for this change
Definition at line 50 of file AbstractChange.java.
{
        this.tagName = tagName;
        this.changeName = changeName;
    }
Member Function Documentation
String liquibase.change.AbstractChange.getChangeName ()
See also:
liquibase.change.Change.getChangeName()
Implements liquibase.change.Change.
Definition at line 68 of file AbstractChange.java.
{
        return changeName;
    }
String liquibase.change.AbstractChange.getTagName ()
See also:
liquibase.change.Change.getTagName()
Implements liquibase.change.Change.
Definition at line 75 of file AbstractChange.java.
Referenced by liquibase.change.RenameViewChange.createNode(), liquibase.change.MergeColumnChange.createNode(), liquibase.change.ExecuteShellCommandChange.createNode(), liquibase.change.DropUniqueConstraintChange.createNode(), liquibase.change.DropPrimaryKeyChange.createNode(), liquibase.change.DropForeignKeyConstraintChange.createNode(), liquibase.change.DropDefaultValueChange.createNode(), liquibase.change.AddUniqueConstraintChange.createNode(), liquibase.change.AddPrimaryKeyChange.createNode(), liquibase.change.AddLookupTableChange.createNode(), liquibase.change.AddForeignKeyConstraintChange.createNode(), and liquibase.change.AddDefaultValueChange.createNode().
{
        return tagName;
    }
void liquibase.change.AbstractChange.executeStatements (Database database) throws JDBCException, UnsupportedChangeException
See also:
liquibase.change.Change.executeStatements(liquibase.database.Database)
Implements liquibase.change.Change.
Definition at line 82 of file AbstractChange.java.
References liquibase.change.Change.generateStatements().
{
        SqlStatement[] statements = generateStatements(database);
        execute(statements, database);
    }
void liquibase.change.AbstractChange.saveStatements (Database database, Writer writer) throws IOException, UnsupportedChangeException, StatementNotSupportedOnDatabaseException
See also:
liquibase.change.Change.saveStatements(liquibase.database.Database, java.io.Writer)
Implements liquibase.change.Change.
Definition at line 91 of file AbstractChange.java.
References liquibase.change.Change.generateStatements().
{
        SqlStatement[] statements = generateStatements(database);
        for (SqlStatement statement : statements) {
            writer.append(statement.getSqlStatement(database)).append(statement.getEndDelimiter(database)).append(StreamUtil.getLineSeparator()).append(StreamUtil.getLineSeparator());
        }
    }
void liquibase.change.AbstractChange.executeRollbackStatements (Database database) throws JDBCException, UnsupportedChangeException, RollbackImpossibleException
See also:
liquibase.change.Change.executeRollbackStatements(liquibase.database.Database)
Implements liquibase.change.Change.
Definition at line 101 of file AbstractChange.java.
References liquibase.change.AbstractChange.generateRollbackStatements().
{
        SqlStatement[] statements = generateRollbackStatements(database);
        execute(statements, database);
    }
void liquibase.change.AbstractChange.saveRollbackStatement (Database database, Writer writer) throws IOException, UnsupportedChangeException, RollbackImpossibleException, StatementNotSupportedOnDatabaseException
See also:
liquibase.change.Change.saveRollbackStatement(liquibase.database.Database, java.io.Writer)
Implements liquibase.change.Change.
Definition at line 109 of file AbstractChange.java.
References liquibase.change.AbstractChange.generateRollbackStatements().
{
        SqlStatement[] statements = generateRollbackStatements(database);
        for (SqlStatement statement : statements) {
            writer.append(statement.getSqlStatement(database)).append(";\n\n");
        }
    }
SqlStatement [] liquibase.change.AbstractChange.generateRollbackStatements (Database database) throws UnsupportedChangeException, RollbackImpossibleException
See also:
liquibase.change.Change.generateRollbackStatements(liquibase.database.Database)
Implements liquibase.change.Change.
Reimplemented in liquibase.change.custom.CustomChangeWrapper.
Definition at line 125 of file AbstractChange.java.
Referenced by liquibase.change.AbstractChange.executeRollbackStatements(), and liquibase.change.AbstractChange.saveRollbackStatement().
{
        return generateRollbackStatementsFromInverse(database);
    }
boolean liquibase.change.AbstractChange.canRollBack ()
See also:
liquibase.change.Change.canRollBack()
Implements liquibase.change.Change.
Reimplemented in liquibase.change.custom.CustomChangeWrapper.
Definition at line 132 of file AbstractChange.java.
{
        return createInverses() != null;
    }
String liquibase.change.AbstractChange.getMD5Sum ()
See also:
liquibase.change.Change.getMD5Sum()
Implements liquibase.change.Change.
Reimplemented in liquibase.change.SQLFileChange.
Definition at line 151 of file AbstractChange.java.
References liquibase.change.Change.createNode().
{
        try {
            StringBuffer buffer = new StringBuffer();
            nodeToStringBuffer(createNode(DocumentBuilderFactory.newInstance().newDocumentBuilder().newDocument()), buffer);
            return MD5Util.computeMD5(buffer.toString());
        } catch (ParserConfigurationException e) {
            throw new RuntimeException(e);
        }
    }
FileOpener liquibase.change.AbstractChange.getFileOpener ()
Returns the FileOpen as provided by the creating ChangeLog.
Returns:
The file opener
Definition at line 256 of file AbstractChange.java.
{
        return fileOpener;
    }
void liquibase.change.AbstractChange.setUp () throws SetupException
Most Changes don't need to do any setup.
This implements a no-op
Implements liquibase.change.Change.
Reimplemented in liquibase.change.SQLFileChange.
Definition at line 264 of file AbstractChange.java.
{
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AbstractChange.java