LiquiBase: liquibase.change.DropDefaultValueChange Class Reference
liquibase.change.DropDefaultValueChange
liquibase.change.DropDefaultValueChange Class Reference
Detailed Description
Removes the default value from an existing column.
Definition at line 20 of file DropDefaultValueChange.java.
Public Member Functions
DropDefaultValueChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getColumnName ()
void setColumnName (String columnName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.DropDefaultValueChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 54 of file DropDefaultValueChange.java.
References liquibase.change.DropDefaultValueChange.getColumnName(), liquibase.change.DropDefaultValueChange.getSchemaName(), and liquibase.change.DropDefaultValueChange.getTableName().
{
        return new SqlStatement[]{
                new DropDefaultValueStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName(), getColumnName()),
        };
    }
String liquibase.change.DropDefaultValueChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 61 of file DropDefaultValueChange.java.
References liquibase.change.DropDefaultValueChange.getColumnName(), and liquibase.change.DropDefaultValueChange.getTableName().
{
        return "Default value dropped from "+getTableName()+"."+getColumnName();
    }
Element liquibase.change.DropDefaultValueChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 65 of file DropDefaultValueChange.java.
References liquibase.change.DropDefaultValueChange.getColumnName(), liquibase.change.DropDefaultValueChange.getSchemaName(), liquibase.change.DropDefaultValueChange.getTableName(), and liquibase.change.AbstractChange.getTagName().
{
        Element node = currentChangeLogFileDOM.createElement(getTagName());
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        node.setAttribute("columnName", getColumnName());
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DropDefaultValueChange.java