LiquiBase: liquibase.change.CreateTableChange Class Reference
liquibase.change.CreateTableChange
liquibase.change.CreateTableChange Class Reference
Detailed Description
Creates a new table.
Definition at line 21 of file CreateTableChange.java.
Public Member Functions
CreateTableChange ()
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
List< ColumnConfig > getColumns ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getTablespace ()
void setTablespace (String tablespace)
void addColumn (ColumnConfig column)
String getRemarks ()
void setRemarks (String remarks)
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.CreateTableChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 34 of file CreateTableChange.java.
References liquibase.database.sql.CreateTableStatement.addColumn(), liquibase.database.sql.CreateTableStatement.addColumnConstraint(), liquibase.database.sql.CreateTableStatement.addPrimaryKeyColumn(), liquibase.change.CreateTableChange.getColumns(), liquibase.change.ConstraintsConfig.getForeignKeyName(), liquibase.change.ConstraintsConfig.getReferences(), liquibase.change.CreateTableChange.getSchemaName(), liquibase.change.CreateTableChange.getTableName(), liquibase.change.CreateTableChange.getTablespace(), liquibase.change.ConstraintsConfig.getUniqueConstraintName(), liquibase.change.ConstraintsConfig.isDeferrable(), liquibase.change.ConstraintsConfig.isDeleteCascade(), liquibase.change.ConstraintsConfig.isInitiallyDeferred(), liquibase.change.ConstraintsConfig.isNullable(), liquibase.change.ConstraintsConfig.isPrimaryKey(), liquibase.change.ConstraintsConfig.isUnique(), liquibase.database.sql.ForeignKeyConstraint.setColumn(), liquibase.database.sql.ForeignKeyConstraint.setDeferrable(), liquibase.database.sql.ForeignKeyConstraint.setDeleteCascade(), liquibase.database.sql.ForeignKeyConstraint.setInitiallyDeferred(), and liquibase.database.sql.CreateTableStatement.setTablespace().
{
        String schemaName = getSchemaName() == null ? database.getDefaultSchemaName() : getSchemaName();
        CreateTableStatement statement = new CreateTableStatement(schemaName, getTableName());
        for (ColumnConfig column : getColumns()) {
            ConstraintsConfig constraints = column.getConstraints();
            boolean isAutoIncrement = column.isAutoIncrement() != null && column.isAutoIncrement();
            if (constraints != null && constraints.isPrimaryKey() != null && constraints.isPrimaryKey()) {
                statement.addPrimaryKeyColumn(column.getName(),
                        database.getColumnType(column.getType(), isAutoIncrement));
            } else {
                String defaultValue = null;
                if (column.hasDefaultValue()) {
                    defaultValue = StringUtils.trimToNull(column.getDefaultColumnValue(database));
                }
                statement.addColumn(column.getName(),
                        database.getColumnType(column.getType(), column.isAutoIncrement()),
                        defaultValue);
            }
            if (constraints != null) {
                if (constraints.isNullable() != null && !constraints.isNullable()) {
                    statement.addColumnConstraint(new NotNullConstraint(column.getName()));
                }
                if (constraints.getReferences() != null) {
                    if (StringUtils.trimToNull(constraints.getForeignKeyName()) == null) {
                        throw new UnsupportedChangeException("createTable with references requires foreignKeyName");
                    }
                    ForeignKeyConstraint fkConstraint = new ForeignKeyConstraint(constraints.getForeignKeyName(), constraints.getReferences());
                    fkConstraint.setColumn(column.getName());
                    fkConstraint.setDeleteCascade(constraints.isDeleteCascade() != null && constraints.isDeleteCascade());
                    fkConstraint.setInitiallyDeferred(constraints.isInitiallyDeferred() != null && constraints.isInitiallyDeferred());
                    fkConstraint.setDeferrable(constraints.isDeferrable() != null && constraints.isDeferrable());
                    statement.addColumnConstraint(fkConstraint);
                }
                if (constraints.isUnique() != null && constraints.isUnique()) {
                    statement.addColumnConstraint(new UniqueConstraint(constraints.getUniqueConstraintName()).addColumns(column.getName()));
                }
            }
            if (isAutoIncrement) {
                statement.addColumnConstraint(new AutoIncrementConstraint(column.getName()));
            }
        }
        statement.setTablespace(StringUtils.trimToNull(getTablespace()));
        List<SqlStatement> statements = new ArrayList<SqlStatement>();
        statements.add(statement);
        return statements.toArray(new SqlStatement[statements.size()]);
    }
String liquibase.change.CreateTableChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 143 of file CreateTableChange.java.
{
        return "Table " + tableName + " created";
    }
Element liquibase.change.CreateTableChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 147 of file CreateTableChange.java.
References liquibase.change.CreateTableChange.getColumns(), liquibase.change.CreateTableChange.getSchemaName(), and liquibase.change.CreateTableChange.getTableName().
{
        Element element = currentChangeLogFileDOM.createElement("createTable");
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("tableName", getTableName());
        if (StringUtils.trimToNull(tablespace) != null) {
            element.setAttribute("tablespace", tablespace);
        }
        if (StringUtils.trimToNull(remarks) != null) {
            element.setAttribute("remarks", remarks);
        }
        for (ColumnConfig column : getColumns()) {
            element.appendChild(column.createNode(currentChangeLogFileDOM));
        }
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/CreateTableChange.java