LiquiBase: liquibase.change.DropUniqueConstraintChange Class Reference
liquibase.change.DropUniqueConstraintChange
liquibase.change.DropUniqueConstraintChange Class Reference
Detailed Description
Removes an existing unique constraint.
Definition at line 18 of file DropUniqueConstraintChange.java.
Public Member Functions
DropUniqueConstraintChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getConstraintName ()
void setConstraintName (String constraintName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.DropUniqueConstraintChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 51 of file DropUniqueConstraintChange.java.
References liquibase.change.DropUniqueConstraintChange.getConstraintName(), liquibase.change.DropUniqueConstraintChange.getSchemaName(), and liquibase.change.DropUniqueConstraintChange.getTableName().
{
        return new SqlStatement[]{
                new DropUniqueConstraintStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName(), getConstraintName()),
        };
    }
String liquibase.change.DropUniqueConstraintChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 57 of file DropUniqueConstraintChange.java.
References liquibase.change.DropUniqueConstraintChange.getConstraintName(), and liquibase.change.DropUniqueConstraintChange.getTableName().
{
        return "Unique constraint "+getConstraintName()+" dropped from "+getTableName();
    }
Element liquibase.change.DropUniqueConstraintChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 61 of file DropUniqueConstraintChange.java.
References liquibase.change.DropUniqueConstraintChange.getSchemaName(), liquibase.change.DropUniqueConstraintChange.getTableName(), and liquibase.change.AbstractChange.getTagName().
{
        Element node = currentChangeLogFileDOM.createElement(getTagName());
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        node.setAttribute("constraintName", constraintName);
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DropUniqueConstraintChange.java