LiquiBase: liquibase.change.CreateSequenceChange Class Reference
liquibase.change.CreateSequenceChange
liquibase.change.CreateSequenceChange Class Reference
Detailed Description
Creates a new sequence.
Definition at line 19 of file CreateSequenceChange.java.
Public Member Functions
CreateSequenceChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getSequenceName ()
void setSequenceName (String sequenceName)
Integer getStartValue ()
void setStartValue (Integer startValue)
Integer getIncrementBy ()
void setIncrementBy (Integer incrementBy)
Integer getMaxValue ()
void setMaxValue (Integer maxValue)
Integer getMinValue ()
void setMinValue (Integer minValue)
Boolean isOrdered ()
void setOrdered (Boolean ordered)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.CreateSequenceChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 90 of file CreateSequenceChange.java.
References liquibase.change.CreateSequenceChange.getIncrementBy(), liquibase.change.CreateSequenceChange.getMaxValue(), liquibase.change.CreateSequenceChange.getMinValue(), liquibase.change.CreateSequenceChange.getSchemaName(), liquibase.change.CreateSequenceChange.getSequenceName(), liquibase.change.CreateSequenceChange.getStartValue(), liquibase.change.CreateSequenceChange.isOrdered(), liquibase.change.CreateSequenceChange.setIncrementBy(), liquibase.change.CreateSequenceChange.setMaxValue(), liquibase.change.CreateSequenceChange.setMinValue(), liquibase.change.CreateSequenceChange.setOrdered(), and liquibase.change.CreateSequenceChange.setStartValue().
{
        return new SqlStatement[] {
                new CreateSequenceStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getSequenceName())
                .setIncrementBy(getIncrementBy())
                .setMaxValue(getMaxValue())
                .setMinValue(getMinValue())
                .setOrdered(isOrdered())
                .setStartValue(getStartValue())
        };
    }
String liquibase.change.CreateSequenceChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 110 of file CreateSequenceChange.java.
References liquibase.change.CreateSequenceChange.getSequenceName().
{
        return "Sequence " + getSequenceName() + " created";
    }
Element liquibase.change.CreateSequenceChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 114 of file CreateSequenceChange.java.
References liquibase.change.CreateSequenceChange.getIncrementBy(), liquibase.change.CreateSequenceChange.getMaxValue(), liquibase.change.CreateSequenceChange.getMinValue(), liquibase.change.CreateSequenceChange.getSequenceName(), liquibase.change.CreateSequenceChange.getStartValue(), and liquibase.change.CreateSequenceChange.isOrdered().
{
        Element node = currentChangeLogFileDOM.createElement("createSequence");
        node.setAttribute("sequenceName", getSequenceName());
        if (getMinValue() != null) {
            node.setAttribute("minValue", getMinValue().toString());
        }
        if (getMaxValue() != null) {
            node.setAttribute("maxValue", getMaxValue().toString());
        }
        if (getIncrementBy() != null) {
            node.setAttribute("incrementBy", getIncrementBy().toString());
        }
        if (isOrdered() != null) {
            node.setAttribute("ordered", isOrdered().toString());
        }
        if (getStartValue() != null) {
            node.setAttribute("startValue", getStartValue().toString());
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/CreateSequenceChange.java