LiquiBase: liquibase.change.DropTableChange Class Reference
liquibase.change.DropTableChange
liquibase.change.DropTableChange Class Reference
Detailed Description
Drops an existing table.
Definition at line 19 of file DropTableChange.java.
Public Member Functions
DropTableChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
Boolean isCascadeConstraints ()
void setCascadeConstraints (Boolean cascadeConstraints)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.DropTableChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 54 of file DropTableChange.java.
References liquibase.change.DropTableChange.getSchemaName(), liquibase.change.DropTableChange.getTableName(), and liquibase.change.DropTableChange.isCascadeConstraints().
{
        boolean constraints = false;
        if (isCascadeConstraints() != null) {
            constraints = isCascadeConstraints();
        }
        return new SqlStatement[]{
                new DropTableStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName(), constraints)
        };
    }
String liquibase.change.DropTableChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 65 of file DropTableChange.java.
References liquibase.change.DropTableChange.getTableName().
{
        return "Table " + getTableName() + " dropped";
    }
Element liquibase.change.DropTableChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 69 of file DropTableChange.java.
References liquibase.change.DropTableChange.getSchemaName(), liquibase.change.DropTableChange.getTableName(), and liquibase.change.DropTableChange.isCascadeConstraints().
{
        Element element = currentChangeLogFileDOM.createElement("dropTable");
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("tableName", getTableName());
        if (isCascadeConstraints() != null) {
            element.setAttribute("cascadeConstraints", isCascadeConstraints().toString());
        }
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DropTableChange.java