LiquiBase: liquibase.ChangeSet Class Reference
liquibase.ChangeSet Class Reference
Detailed Description
Encapsulates a changeSet and all its associated changes.
Definition at line 27 of file ChangeSet.java.
Public Member Functions
boolean execute (Database database) throws MigrationFailedException
This method will actually execute each of the changes in the list against the specified database.
List< Change > getChanges ()
Returns an unmodifiable list of changes.
Member Function Documentation
boolean liquibase.ChangeSet.execute (Database database) throws MigrationFailedException
This method will actually execute each of the changes in the list against the specified database.
Returns:
should change set be marked as ran
Definition at line 116 of file ChangeSet.java.
References liquibase.ChangeSet.getChanges(), and liquibase.exception.PreconditionFailedException.getFailedPreconditions().
{
        boolean skipChange = false;
        boolean markRan = true;
        try {
            database.getJdbcTemplate().comment("Changeset " + toString());
            if (StringUtils.trimToNull(getComments()) != null) {
                String comments = getComments();
                String[] lines = comments.split("\n");
                for (int i = 0; i < lines.length; i++) {
                    if (i > 0) {
                        lines[i] = database.getLineComment() + " " + lines[i];
                    }
                }
                database.getJdbcTemplate().comment(StringUtils.join(Arrays.asList(lines), "\n"));
            }
            if (database.getJdbcTemplate().executesStatements() && rootPrecondition != null) {
                try {
                    rootPrecondition.check(database, null);
                } catch (PreconditionFailedException e) {
                    StringBuffer message = new StringBuffer();
                    message.append(StreamUtil.getLineSeparator());
                    for (FailedPrecondition invalid : e.getFailedPreconditions()) {
                        message.append("          ").append(invalid.toString());
                        message.append(StreamUtil.getLineSeparator());
                    }
                    if (rootPrecondition.getOnFail().equals(Preconditions.FailOption.HALT)) {
                        e.printStackTrace();
                        throw new MigrationFailedException(this, message.toString());
                    } else if (rootPrecondition.getOnFail().equals(Preconditions.FailOption.CONTINUE)) {
                        skipChange = true;
                        markRan = false;
                        log.log(Level.INFO, "Continuing past ChangeSet: " + toString() +" due to precondition failure: " + message);
                    } else if (rootPrecondition.getOnFail().equals(Preconditions.FailOption.MARK_RAN)) {
                        skipChange = true;
                        log.log(Level.INFO, "Marking ChangeSet: " + toString() +" ran due to precondition failure: " + message);
                    } else if (rootPrecondition.getOnFail().equals(Preconditions.FailOption.WARN)) {
                        log.log(Level.WARNING, "Running change set despite failed precondition.  ChangeSet: " + toString() + ": " + message);
                    } else {
                        throw new MigrationFailedException(this, "Unexpected precondition onFail attribute: "+rootPrecondition.getOnFail());
                    }
                } catch (PreconditionErrorException e) {
                    StringBuffer message = new StringBuffer();
                    message.append(StreamUtil.getLineSeparator());
                    for (ErrorPrecondition invalid : e.getErrorPreconditions()) {
                        message.append("          ").append(invalid.toString());
                        message.append(StreamUtil.getLineSeparator());
                    }
                    if (rootPrecondition.getOnError().equals(Preconditions.ErrorOption.HALT)) {
                        throw new MigrationFailedException(this, message.toString());
                    } else if (rootPrecondition.getOnError().equals(Preconditions.ErrorOption.CONTINUE)) {
                        skipChange = true;
                        markRan = false;
                        log.log(Level.INFO, "Continuing past ChangeSet: " + toString() +" due to precondition error: " + message);
                    } else if (rootPrecondition.getOnError().equals(Preconditions.ErrorOption.MARK_RAN)) {
                        skipChange = true;
                        markRan = true;
                        log.log(Level.INFO, "Marking ChangeSet: " + toString() +" due ran to precondition error: " + message);
                    } else if (rootPrecondition.getOnError().equals(Preconditions.ErrorOption.WARN)) {
                        log.log(Level.WARNING, "Running change set despite errored precondition.  ChangeSet: " + toString() + ": " + message);
                    } else {
                        throw new MigrationFailedException(this, "Unexpected precondition onError attribute: "+rootPrecondition.getOnError());
                    }
                    database.rollback();
                }
            }
            if (!skipChange) {
                for (Change change : changes) {
                    try {
                        change.setUp();
                    } catch (SetupException se) {
                        throw new MigrationFailedException(this, se);
                    }
                }
                log.finest("Reading ChangeSet: " + toString());
                for (Change change : getChanges()) {
                    change.executeStatements(database);
                    log.finest(change.getConfirmationMessage());
                }
                database.commit();
                log.finest("ChangeSet " + toString() + " has been successfully run.");
                database.commit();
            } else {
                log.finest("Skipping ChangeSet: " + toString());
            }
        } catch (Exception e) {
            try {
                database.rollback();
            } catch (Exception e1) {
                throw new MigrationFailedException(this, e);
            }
            if (getFailOnError() != null && !getFailOnError()) {
                log.log(Level.INFO, "Change set " + toString(false) + " failed, but failOnError was false", e);
            } else {
                if (e instanceof MigrationFailedException) {
                    throw ((MigrationFailedException) e);
                } else {
                    throw new MigrationFailedException(this, e);
                }
            }
        }
        return markRan;
    }
List<Change> liquibase.ChangeSet.getChanges ()
Returns an unmodifiable list of changes.
To add one, use the addRefactoing method.
Definition at line 273 of file ChangeSet.java.
Referenced by liquibase.ChangeSet.execute().
{
        return Collections.unmodifiableList(changes);
    }
The documentation for this class was generated from the following file:
java/liquibase/ChangeSet.java