LiquiBase: liquibase.change.DropSequenceChange Class Reference
liquibase.change.DropSequenceChange
liquibase.change.DropSequenceChange Class Reference
Detailed Description
Drops an existing sequence.
Definition at line 19 of file DropSequenceChange.java.
Public Member Functions
DropSequenceChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getSequenceName ()
void setSequenceName (String sequenceName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.DropSequenceChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 44 of file DropSequenceChange.java.
References liquibase.change.DropSequenceChange.getSchemaName(), and liquibase.change.DropSequenceChange.getSequenceName().
{
        return new SqlStatement[]{new DropSequenceStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getSequenceName())};
    }
String liquibase.change.DropSequenceChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 48 of file DropSequenceChange.java.
References liquibase.change.DropSequenceChange.getSequenceName().
{
        return "Sequence " + getSequenceName() + " dropped";
    }
Element liquibase.change.DropSequenceChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 52 of file DropSequenceChange.java.
References liquibase.change.DropSequenceChange.getSchemaName(), and liquibase.change.DropSequenceChange.getSequenceName().
{
        Element element = currentChangeLogFileDOM.createElement("dropSequence");
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("sequenceName", getSequenceName());
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DropSequenceChange.java