LiquiBase: liquibase.change.AddNotNullConstraintChange Class Reference
liquibase.change.AddNotNullConstraintChange
liquibase.change.AddNotNullConstraintChange Class Reference
Detailed Description
Adds a not-null constraint to an existing column.
Definition at line 21 of file AddNotNullConstraintChange.java.
Public Member Functions
AddNotNullConstraintChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getColumnName ()
void setColumnName (String columnName)
String getDefaultNullValue ()
void setDefaultNullValue (String defaultNullValue)
String getColumnDataType ()
void setColumnDataType (String columnDataType)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.AddNotNullConstraintChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 74 of file AddNotNullConstraintChange.java.
References liquibase.change.AddNotNullConstraintChange.getColumnDataType(), liquibase.change.AddNotNullConstraintChange.getColumnName(), liquibase.change.AddNotNullConstraintChange.getDefaultNullValue(), liquibase.change.AddNotNullConstraintChange.getSchemaName(), and liquibase.change.AddNotNullConstraintChange.getTableName().
Referenced by liquibase.change.AddLookupTableChange.generateStatements().
{
        List<SqlStatement> statements = new ArrayList<SqlStatement>();
        String schemaName = getSchemaName() == null?database.getDefaultSchemaName():getSchemaName();
        if (defaultNullValue != null) {
            statements.add(new UpdateStatement(schemaName, getTableName())
                    .addNewColumnValue(getColumnName(), getDefaultNullValue())
                    .setWhereClause(getColumnName() + " IS NULL"));
        }
        statements.add(new SetNullableStatement(schemaName, getTableName(), getColumnName(), getColumnDataType(), false));
        if (database instanceof DB2Database) {
            statements.add(new ReorganizeTableStatement(schemaName, getTableName()));
        }
        return statements.toArray(new SqlStatement[statements.size()]);
    }
String liquibase.change.AddNotNullConstraintChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 106 of file AddNotNullConstraintChange.java.
References liquibase.change.AddNotNullConstraintChange.getColumnName(), and liquibase.change.AddNotNullConstraintChange.getTableName().
{
        return "Null constraint has been added to " + getTableName() + "." + getColumnName();
    }
Element liquibase.change.AddNotNullConstraintChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 111 of file AddNotNullConstraintChange.java.
References liquibase.change.AddNotNullConstraintChange.getColumnName(), liquibase.change.AddNotNullConstraintChange.getDefaultNullValue(), liquibase.change.AddNotNullConstraintChange.getSchemaName(), and liquibase.change.AddNotNullConstraintChange.getTableName().
{
        Element element = currentChangeLogFileDOM.createElement("addNotNullConstraint");
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("tableName", getTableName());
        element.setAttribute("columnName", getColumnName());
        element.setAttribute("defaultNullValue", getDefaultNullValue());
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AddNotNullConstraintChange.java