LiquiBase: liquibase.spring.SpringLiquibase Class Reference
liquibase.spring.SpringLiquibase
liquibase.spring.SpringLiquibase Class Reference
Detailed Description
A Spring-ified wrapper for Liquibase.
Example Configuration:
This Spring configuration example will cause liquibase to run automatically when the Spring context is initialized. It will load db-changelog.xml from the classpath and apply it against myDataSource.
 <bean id="myLiquibase"
          class="liquibase.spring.SpringLiquibase"
          >
      <property name="dataSource" ref="myDataSource" />
      <property name="changeLog" value="classpath:db-changelog.xml" />
      <!-- The following configuration options are optional -->
      <property name="executeEnabled" value="true" />
      <!--
      If set to true, writeSqlFileEnabled will write the generated
      SQL to a file before executing it.
      -->
      <property name="writeSqlFileEnabled" value="true" />
      <!--
      sqlOutputDir specifies the directory into which the SQL file
      will be written, if so configured.
      -->
      <property name="sqlOutputDir" value="c:" />
 </bean>
Author:
Rob Schoening
Definition at line 73 of file SpringLiquibase.java.
Public Member Functions
SpringLiquibase ()
String getDatabaseProductName () throws JDBCException
DataSource getDataSource ()
The DataSource that liquibase will use to perform the migration.
void setDataSource (DataSource dataSource)
The DataSource that liquibase will use to perform the migration.
void setExecuteEnabled (boolean executeSql)
Determines whether liquibase will actually execute DDL statements.
boolean isExecuteEnabled ()
Determines whether liquibase will actually execute DDL statements.
String getExecuteDisabledWarningMessage ()
Returns a warning message that will be written out to the log.
File getSqlOutputDir ()
Returns the output directory into which a SQL file will be written *if* writeSqlFileEnabled is set to true.
void setSqlOutputDir (File sqlOutputDir)
Sets the output directory into which a SQL file will be written if writeSqlFileEnabled is also set to true.
String getChangeLog ()
Returns a Resource that is able to resolve to a file or classpath resource.
void setChangeLog (String dataModel)
Sets a Spring Resource that is able to resolve to a file or classpath resource.
String getContexts ()
void setContexts (String contexts)
void afterPropertiesSet () throws LiquibaseException
Executed automatically when the bean is initialized.
boolean isWriteSqlFileEnabled ()
Boolean flag to determine whether generated SQL should be written to disk.
void setWriteSqlFileEnabled (boolean writeSqlFile)
Boolean flag to determine whether generated SQL should be written to disk.
void setBeanName (String name)
Spring sets this automatically to the instance's configured bean name.
String getBeanName ()
Gets the Spring-name of this instance.
void setResourceLoader (ResourceLoader resourceLoader)
ResourceLoader getResourceLoader ()
Protected Member Functions
void writeSqlFile (Liquibase liquibase) throws LiquibaseException
If there are any un-run changesets, this method will write them out to a file, if so configured.
void executeSql (Liquibase liquibase) throws LiquibaseException
This method will actually execute the changesets.
Classes
class SpringResourceOpener
Member Function Documentation
DataSource liquibase.spring.SpringLiquibase.getDataSource ()
The DataSource that liquibase will use to perform the migration.
Returns:
Definition at line 165 of file SpringLiquibase.java.
Referenced by liquibase.spring.SpringLiquibase.afterPropertiesSet(), and liquibase.spring.SpringLiquibase.getDatabaseProductName().
{
        return dataSource;
    }
void liquibase.spring.SpringLiquibase.setExecuteEnabled (boolean executeSql)
Determines whether liquibase will actually execute DDL statements.
Parameters:
executeSql
Definition at line 181 of file SpringLiquibase.java.
{
        this.executeEnabled = executeSql;
    }
String liquibase.spring.SpringLiquibase.getExecuteDisabledWarningMessage ()
Returns a warning message that will be written out to the log.
It is here so that it can be customized.
Returns:
Definition at line 198 of file SpringLiquibase.java.
References liquibase.spring.SpringLiquibase.getBeanName().
Referenced by liquibase.spring.SpringLiquibase.afterPropertiesSet().
{
        return "\n\nYou have set "
                + getBeanName()
                + ".executeEnabled=false, but there are \n"
                + "database change sets that need to be run in order to bring the database up to date.\n"
                + "The application may not behave properly until these changes are run.\n\n";
    }
File liquibase.spring.SpringLiquibase.getSqlOutputDir ()
Returns the output directory into which a SQL file will be written *if* writeSqlFileEnabled is set to true.
Returns:
Definition at line 213 of file SpringLiquibase.java.
Referenced by liquibase.spring.SpringLiquibase.afterPropertiesSet(), and liquibase.spring.SpringLiquibase.writeSqlFile().
{
        return sqlOutputDir;
    }
void liquibase.spring.SpringLiquibase.setSqlOutputDir (File sqlOutputDir)
Sets the output directory into which a SQL file will be written if writeSqlFileEnabled is also set to true.
Parameters:
sqlOutputDir
Definition at line 223 of file SpringLiquibase.java.
{
        this.sqlOutputDir = sqlOutputDir;
    }
String liquibase.spring.SpringLiquibase.getChangeLog ()
Returns a Resource that is able to resolve to a file or classpath resource.
Returns:
Definition at line 232 of file SpringLiquibase.java.
{
        return changeLog;
    }
void liquibase.spring.SpringLiquibase.setChangeLog (String dataModel)
Sets a Spring Resource that is able to resolve to a file or classpath resource.
An example might be classpath:db-changelog.xml.
Definition at line 240 of file SpringLiquibase.java.
{
        this.changeLog = dataModel;
    }
void liquibase.spring.SpringLiquibase.writeSqlFile (Liquibase liquibase) throws LiquibaseException [protected]
If there are any un-run changesets, this method will write them out to a file, if so configured.
Parameters:
liquibase
Exceptions:
SQLException
IOException
LiquibaseException
Definition at line 298 of file SpringLiquibase.java.
References liquibase.spring.SpringLiquibase.getContexts(), liquibase.spring.SpringLiquibase.getDatabaseProductName(), and liquibase.spring.SpringLiquibase.getSqlOutputDir().
Referenced by liquibase.spring.SpringLiquibase.afterPropertiesSet().
{
        FileWriter fw = null;
        try {
            File ddlDir = getSqlOutputDir();
            ddlDir.mkdirs();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmss");
            sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
            String dateString = sdf.format(new java.util.Date());
            String fileString = (getDatabaseProductName() + "-" + dateString + ".sql").replace(" ", "-").toLowerCase();
            File upgradeFile = new File(ddlDir, fileString);
            fw = new FileWriter(upgradeFile);
            liquibase.update(getContexts(), fw);
        } catch (IOException e) {
            throw new LiquibaseException(e);
        } finally {
            if (fw != null) {
                try {
                    fw.close();
                } catch (IOException e) {
                    log.log(Level.SEVERE, "error closing fileWriter", e);
                }
            }
        }
    }
void liquibase.spring.SpringLiquibase.executeSql (Liquibase liquibase) throws LiquibaseException [protected]
This method will actually execute the changesets.
Parameters:
liquibase
Exceptions:
SQLException
IOException
Definition at line 338 of file SpringLiquibase.java.
References liquibase.spring.SpringLiquibase.getContexts().
Referenced by liquibase.spring.SpringLiquibase.afterPropertiesSet().
{
        liquibase.update(getContexts());
    }
boolean liquibase.spring.SpringLiquibase.isWriteSqlFileEnabled ()
Boolean flag to determine whether generated SQL should be written to disk.
Returns:
Definition at line 347 of file SpringLiquibase.java.
Referenced by liquibase.spring.SpringLiquibase.afterPropertiesSet().
{
        return writeSqlFileEnabled;
    }
String liquibase.spring.SpringLiquibase.getBeanName ()
Gets the Spring-name of this instance.
Returns:
Definition at line 371 of file SpringLiquibase.java.
Referenced by liquibase.spring.SpringLiquibase.getExecuteDisabledWarningMessage().
{
        return beanName;
    }
The documentation for this class was generated from the following file:
java/liquibase/spring/SpringLiquibase.java