LiquiBase: liquibase.change.AbstractSQLChange Class Reference
liquibase.change.AbstractSQLChange Class Reference
Detailed Description
A common parent for all SQL related changes regardless of where the sql was sourced from.
Implements the necessary logic to choose how it should be parsed to generate the statements.
Author:
Paul Keeble
Definition at line 21 of file AbstractSQLChange.java.
Public Member Functions
void setStripComments (Boolean stripComments)
boolean isStrippingComments ()
void setSplitStatements (Boolean splitStatements)
If set to true then the sql will be split around any ; and
entries in the sql and each line provided as a separate statement.
boolean isSplittingStatements ()
void setSql (String sql)
The raw SQL to use for this change.
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates one or more statements depending on how the SQL should be parsed.
Member Function Documentation
void liquibase.change.AbstractSQLChange.setStripComments (Boolean stripComments)
Parameters:
stripComments true if comments should be stripped out, otherwise false
Definition at line 38 of file AbstractSQLChange.java.
{
        this.stripComments = stripComments;
    }
boolean liquibase.change.AbstractSQLChange.isStrippingComments ()
Returns:
true if stripping comments, otherwise false
Definition at line 46 of file AbstractSQLChange.java.
Referenced by liquibase.change.AbstractSQLChange.generateStatements().
{
        return stripComments;
    }
void liquibase.change.AbstractSQLChange.setSplitStatements (Boolean splitStatements)
If set to true then the sql will be split around any ; and
entries in the sql and each line provided as a separate statement.
Parameters:
splitStatements set true if the SQL should be split, otherwise false
Definition at line 56 of file AbstractSQLChange.java.
{
        this.splitStatements = splitStatements;
    }
boolean liquibase.change.AbstractSQLChange.isSplittingStatements ()
Returns:
true if a multi-line file will be split, otherwise false
Definition at line 64 of file AbstractSQLChange.java.
Referenced by liquibase.change.AbstractSQLChange.generateStatements().
{
        return splitStatements;
    }
SqlStatement [] liquibase.change.AbstractSQLChange.generateStatements (Database database) throws UnsupportedChangeException
Generates one or more statements depending on how the SQL should be parsed.
If split statements is set to true then the SQL is split on the ; and go
entries found in the sql text and each is made a separate statement.
If stripping comments is true then any comments after -- on a line and any comments between /* and \*\/ will be stripped before the splitting is executed.
The end result is one or more SQL statements split in the way the user requested
Implements liquibase.change.Change.
Definition at line 104 of file AbstractSQLChange.java.
References liquibase.change.AbstractSQLChange.isSplittingStatements(), and liquibase.change.AbstractSQLChange.isStrippingComments().
{
        List<SqlStatement> returnStatements = new ArrayList<SqlStatement>();
        String processedSQL = isStrippingComments() ? StringUtils.stripComments(getSql()) : getSql();
        processedSQL = processedSQL.replaceAll("\r\n", "\n").replaceAll("\r", "\n");
        if(isSplittingStatements()) {
            String[] statements = StringUtils.splitSQL(processedSQL);
            for (String statement : statements) {
                returnStatements.add(new RawSqlStatement(statement, getEndDelimiter()));
            }
        } else {
            returnStatements.add(new RawSqlStatement(processedSQL, getEndDelimiter()));
        }
        return returnStatements.toArray(new SqlStatement[returnStatements.size()]);
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AbstractSQLChange.java