LiquiBase: liquibase.database.template.JdbcTemplate Class Reference
liquibase.database.template.JdbcTemplate
liquibase.database.template.JdbcTemplate Class Reference
Detailed Description
Class to simplify execution of SqlStatements.
Based heavily on Spring's JdbcTemplate.
Note: This class is currently intended for LiquiBase-internal use only and may change without notice in the future
Definition at line 26 of file JdbcTemplate.java.
Public Member Functions
JdbcTemplate (Database database)
boolean executesStatements ()
Object execute (StatementCallback action) throws JDBCException
void execute (final SqlStatement sql) throws JDBCException
Object query (final SqlStatement sql, final ResultSetExtractor rse) throws JDBCException
List query (SqlStatement sql, RowMapper rowMapper) throws JDBCException
Object queryForObject (SqlStatement sql, RowMapper rowMapper) throws JDBCException
Object queryForObject (SqlStatement sql, Class requiredType) throws JDBCException
long queryForLong (SqlStatement sql) throws JDBCException
int queryForInt (SqlStatement sql) throws JDBCException
List queryForList (SqlStatement sql, Class elementType) throws JDBCException
List< Map > queryForList (SqlStatement sql) throws JDBCException
int update (final SqlStatement sql) throws JDBCException
Object execute (CallableSqlStatement csc, CallableStatementCallback action) throws JDBCException
Map call (CallableSqlStatement csc, final List declaredParameters) throws JDBCException
void comment (String message) throws JDBCException
Adds a comment to the database.
Protected Member Functions
RowMapper getColumnMapRowMapper ()
Create a new RowMapper for reading columns as key-value pairs.
RowMapper getSingleColumnRowMapper (Class requiredType)
Create a new RowMapper for reading result objects from a single column.
Protected Attributes
Database database
Member Function Documentation
RowMapper liquibase.database.template.JdbcTemplate.getColumnMapRowMapper () [protected]
Create a new RowMapper for reading columns as key-value pairs.
Returns:
the RowMapper to use
See also:
ColumnMapRowMapper
Definition at line 201 of file JdbcTemplate.java.
{
        return new ColumnMapRowMapper();
    }
RowMapper liquibase.database.template.JdbcTemplate.getSingleColumnRowMapper (Class requiredType) [protected]
Create a new RowMapper for reading result objects from a single column.
Parameters:
requiredType the type that each result object is expected to match
Returns:
the RowMapper to use
See also:
SingleColumnRowMapper
Definition at line 212 of file JdbcTemplate.java.
{
        return new SingleColumnRowMapper(requiredType);
    }
void liquibase.database.template.JdbcTemplate.comment (String message) throws JDBCException
Adds a comment to the database.
Currently does nothing but is over-ridden in the output JDBC template
Parameters:
message
Exceptions:
JDBCException
Reimplemented in liquibase.database.template.JdbcOutputTemplate.
Definition at line 221 of file JdbcTemplate.java.
Referenced by liquibase.lock.LockHandler.acquireLock(), liquibase.database.AbstractDatabase.checkDatabaseChangeLogLockTable(), liquibase.database.AbstractDatabase.checkDatabaseChangeLogTable(), and liquibase.lock.LockHandler.releaseLock().
{
        LogFactory.getLogger().info(message);
    }
The documentation for this class was generated from the following file:
java/liquibase/database/template/JdbcTemplate.java