LiquiBase: liquibase.util.NumberUtils Class Reference
liquibase.util.NumberUtils Class Reference
Detailed Description
Miscellaneous utility methods for number conversion and parsing.
Mainly for internal use within the framework; consider Jakarta's Commons Lang for a more comprehensive suite of string utilities.
Author:
Juergen Hoeller
Rob Harrop
Since:
1.1.2
Definition at line 17 of file NumberUtils.java.
Static Public Member Functions
static Number convertNumberToTargetClass (Number number, Class targetClass) throws IllegalArgumentException
Convert the given number into an instance of the given target class.
static Number parseNumber (String text, Class targetClass)
Parse the given text into a number instance of the given target class, using the corresponding default decode methods.
static Number parseNumber (String text, Class targetClass, NumberFormat numberFormat)
Parse the given text into a number instance of the given target class, using the given NumberFormat.
Member Function Documentation
static Number liquibase.util.NumberUtils.convertNumberToTargetClass (Number number, Class targetClass) throws IllegalArgumentException [static]
Convert the given number into an instance of the given target class.
Parameters:
number the number to convert
targetClass the target class to convert to
Returns:
the converted number
Exceptions:
IllegalArgumentException if the target class is not supported (i.e. not a standard Number subclass as included in the JDK)
See also:
java.lang.Byte
java.lang.Short
java.lang.Integer
java.lang.Long
java.math.BigInteger
java.lang.Float
java.lang.Double
java.math.BigDecimal
Definition at line 36 of file NumberUtils.java.
Referenced by liquibase.util.NumberUtils.parseNumber().
{
        if (targetClass.isInstance(number)) {
            return number;
        } else if (targetClass.equals(Byte.class)) {
            long value = number.longValue();
            if (value < Byte.MIN_VALUE || value > Byte.MAX_VALUE) {
                raiseOverflowException(number, targetClass);
            }
            return number.byteValue();
        } else if (targetClass.equals(Short.class)) {
            long value = number.longValue();
            if (value < Short.MIN_VALUE || value > Short.MAX_VALUE) {
                raiseOverflowException(number, targetClass);
            }
            return number.shortValue();
        } else if (targetClass.equals(Integer.class)) {
            long value = number.longValue();
            if (value < Integer.MIN_VALUE || value > Integer.MAX_VALUE) {
                raiseOverflowException(number, targetClass);
            }
            return number.intValue();
        } else if (targetClass.equals(Long.class)) {
            return number.longValue();
        } else if (targetClass.equals(Float.class)) {
            return number.floatValue();
        } else if (targetClass.equals(Double.class)) {
            return number.doubleValue();
        } else if (targetClass.equals(BigInteger.class)) {
            return BigInteger.valueOf(number.longValue());
        } else if (targetClass.equals(BigDecimal.class)) {
            // using BigDecimal(String) here, to avoid unpredictability of BigDecimal(double)
            // (see BigDecimal javadoc for details)
            return new BigDecimal(number.toString());
        } else {
            throw new IllegalArgumentException("Could not convert number [" + number + "] of type [" +
                    number.getClass().getName() + "] to unknown target class [" + targetClass.getName() + "]");
        }
    }
static Number liquibase.util.NumberUtils.parseNumber (String text, Class targetClass) [static]
Parse the given text into a number instance of the given target class, using the corresponding default decode methods.
Trims the input String before attempting to parse the number. Supports numbers in hex format (with leading 0x) and in octal format (with leading 0).
Parameters:
text the text to convert
targetClass the target class to parse into
Returns:
the parsed number
Exceptions:
IllegalArgumentException if the target class is not supported (i.e. not a standard Number subclass as included in the JDK)
See also:
java.lang.Byte.decode
java.lang.Short.decode
java.lang.Integer.decode
java.lang.Long.decode
decodeBigInteger(String)
java.lang.Float.valueOf
java.lang.Double.valueOf
java.math.BigDecimal.BigDecimal(String)
Definition at line 108 of file NumberUtils.java.
Referenced by liquibase.util.NumberUtils.parseNumber().
{
        String trimmed = text.trim();
        if (targetClass.equals(Byte.class)) {
            return Byte.decode(trimmed);
        } else if (targetClass.equals(Short.class)) {
            return Short.decode(trimmed);
        } else if (targetClass.equals(Integer.class)) {
            return Integer.decode(trimmed);
        } else if (targetClass.equals(Long.class)) {
            return Long.decode(trimmed);
        } else if (targetClass.equals(BigInteger.class)) {
            return decodeBigInteger(trimmed);
        } else if (targetClass.equals(Float.class)) {
            return Float.valueOf(trimmed);
        } else if (targetClass.equals(Double.class)) {
            return Double.valueOf(trimmed);
        } else if (targetClass.equals(BigDecimal.class) || targetClass.equals(Number.class)) {
            return new BigDecimal(trimmed);
        } else {
            throw new IllegalArgumentException(
                    "Cannot convert String [" + text + "] to target class [" + targetClass.getName() + "]");
        }
    }
static Number liquibase.util.NumberUtils.parseNumber (String text, Class targetClass, NumberFormat numberFormat) [static]
Parse the given text into a number instance of the given target class, using the given NumberFormat.
Trims the input String before attempting to parse the number.
Parameters:
text the text to convert
targetClass the target class to parse into
numberFormat the NumberFormat to use for parsing (if null, this method falls back to parseNumber(String, Class))
Returns:
the parsed number
Exceptions:
IllegalArgumentException if the target class is not supported (i.e. not a standard Number subclass as included in the JDK)
See also:
java.text.NumberFormat.parse
convertNumberToTargetClass
parseNumber(String,Class)
Definition at line 149 of file NumberUtils.java.
References liquibase.util.NumberUtils.convertNumberToTargetClass(), and liquibase.util.NumberUtils.parseNumber().
{
        if (numberFormat != null) {
            try {
                Number number = numberFormat.parse(text.trim());
                return convertNumberToTargetClass(number, targetClass);
            }
            catch (ParseException ex) {
                throw new IllegalArgumentException(ex.getMessage());
            }
        } else {
            return parseNumber(text, targetClass);
        }
    }
The documentation for this class was generated from the following file:
java/liquibase/util/NumberUtils.java