LiquiBase: liquibase.change.MergeColumnChange Class Reference
liquibase.change.MergeColumnChange Class Reference
Detailed Description
Combines data from two existing columns into a new column and drops the original columns.
Definition at line 25 of file MergeColumnChange.java.
Public Member Functions
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Member Function Documentation
SqlStatement [] liquibase.change.MergeColumnChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 114 of file MergeColumnChange.java.
References liquibase.change.DropColumnChange.generateStatements(), liquibase.change.ColumnConfig.getName(), liquibase.change.DropColumnChange.setColumnName(), liquibase.change.ColumnConfig.setName(), liquibase.change.DropColumnChange.setSchemaName(), liquibase.change.DropColumnChange.setTableName(), and liquibase.change.ColumnConfig.setType().
{
        List<SqlStatement> statements = new ArrayList<SqlStatement>();
        AddColumnChange addNewColumnChange = new AddColumnChange();
        String schemaName = getSchemaName() == null?database.getDefaultSchemaName():getSchemaName();
        addNewColumnChange.setSchemaName(schemaName);
        addNewColumnChange.setTableName(getTableName());
        ColumnConfig columnConfig = new ColumnConfig();
        columnConfig.setName(getFinalColumnName());
        columnConfig.setType(getFinalColumnType());
        addNewColumnChange.addColumn(columnConfig);
        statements.addAll(Arrays.asList(addNewColumnChange.generateStatements(database)));
        String updateStatement = "UPDATE " + database.escapeTableName(schemaName, getTableName()) + " SET " + getFinalColumnName() + " = " + database.getConcatSql(getColumn1Name(), "'"+getJoinString()+"'", getColumn2Name());
        statements.add(new RawSqlStatement(updateStatement));
        if (database instanceof SQLiteDatabase) {
                // SQLite does not support this ALTER TABLE operation until now.
                        // For more information see: http://www.sqlite.org/omitted.html
                        // This is a small work around...
                        // define alter table logic
                AlterTableVisitor rename_alter_visitor = new AlterTableVisitor() {
                        public ColumnConfig[] getColumnsToAdd() {
                                ColumnConfig[] new_columns = new ColumnConfig[1];
                                ColumnConfig new_column = new ColumnConfig();
                        new_column.setName(getFinalColumnName());
                        new_column.setType(getFinalColumnType());
                                new_columns[0] = new ColumnConfig(new_column);
                                return new_columns;
                        }
                        public boolean copyThisColumn(ColumnConfig column) {
                                return !(column.getName().equals(getColumn1Name()) ||
                                                column.getName().equals(getColumn2Name()));
                        }
                        public boolean createThisColumn(ColumnConfig column) {
                                return !(column.getName().equals(getColumn1Name()) ||
                                                column.getName().equals(getColumn2Name()));
                        }
                        public boolean createThisIndex(Index index) {
                                return !(index.getColumns().contains(getColumn1Name()) ||
                                                index.getColumns().contains(getColumn2Name()));
                        }
                };
                try {
                        // alter table
                                statements.addAll(SQLiteDatabase.getAlterTableStatements(
                                                rename_alter_visitor,
                                                database,getSchemaName(),getTableName()));
                } catch (JDBCException e) {
                                e.printStackTrace();
                        }
        } else {
                // ...if it is not a SQLite database
                DropColumnChange dropColumn1Change = new DropColumnChange();
                dropColumn1Change.setSchemaName(schemaName);
                dropColumn1Change.setTableName(getTableName());
                dropColumn1Change.setColumnName(getColumn1Name());
                statements.addAll(Arrays.asList(dropColumn1Change.generateStatements(database)));
                DropColumnChange dropColumn2Change = new DropColumnChange();
                dropColumn2Change.setSchemaName(schemaName);
                dropColumn2Change.setTableName(getTableName());
                dropColumn2Change.setColumnName(getColumn2Name());
                statements.addAll(Arrays.asList(dropColumn2Change.generateStatements(database)));
        }
        return statements.toArray(new SqlStatement[statements.size()]);
    }
String liquibase.change.MergeColumnChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 194 of file MergeColumnChange.java.
{
        return "Columns "+getTableName()+"."+getColumn1Name()+" and "+getTableName()+"."+getColumn2Name()+" merged";
    }
Element liquibase.change.MergeColumnChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 198 of file MergeColumnChange.java.
References liquibase.change.AbstractChange.getTagName().
{
        Element element = currentChangeLogFileDOM.createElement(getTagName());
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("tableName", getTableName());
        element.setAttribute("column1Name", getColumn1Name());
        element.setAttribute("joinString", getJoinString());
        element.setAttribute("column2Name", getColumn2Name());
        element.setAttribute("finalColumnName", getFinalColumnName());
        element.setAttribute("finalColumnType", getFinalColumnType());
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/MergeColumnChange.java