LiquiBase: liquibase.change.DeleteDataChange Class Reference
liquibase.change.DeleteDataChange
liquibase.change.DeleteDataChange Class Reference
Detailed Description
Definition at line 17 of file DeleteDataChange.java.
Public Member Functions
DeleteDataChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getWhereClause ()
void setWhereClause (String whereClause)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.DeleteDataChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 51 of file DeleteDataChange.java.
References liquibase.change.DeleteDataChange.getSchemaName(), liquibase.change.DeleteDataChange.getTableName(), and liquibase.database.sql.DeleteStatement.setWhereClause().
{
        DeleteStatement statement = new DeleteStatement(getSchemaName() == null ? database.getDefaultSchemaName() : getSchemaName(), getTableName());
        statement.setWhereClause(whereClause);
        return new SqlStatement[]{
                statement
        };
    }
String liquibase.change.DeleteDataChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 62 of file DeleteDataChange.java.
References liquibase.change.DeleteDataChange.getTableName().
{
        return "Data deleted from " + getTableName();
    }
Element liquibase.change.DeleteDataChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 66 of file DeleteDataChange.java.
References liquibase.change.DeleteDataChange.getSchemaName(), liquibase.change.DeleteDataChange.getTableName(), and liquibase.change.DeleteDataChange.getWhereClause().
{
        Element node = currentChangeLogFileDOM.createElement("delete");
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        if (StringUtils.trimToNull(getWhereClause()) != null) {
            Element whereClause = currentChangeLogFileDOM.createElement("where");
            whereClause.appendChild(currentChangeLogFileDOM.createTextNode(getWhereClause()));
            node.appendChild(whereClause);
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DeleteDataChange.java