LiquiBase: liquibase.change.AddUniqueConstraintChange Class Reference
liquibase.change.AddUniqueConstraintChange
liquibase.change.AddUniqueConstraintChange Class Reference
Detailed Description
Adds a unique constraint to an existing column.
Definition at line 19 of file AddUniqueConstraintChange.java.
Public Member Functions
AddUniqueConstraintChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getColumnNames ()
void setColumnNames (String columnNames)
String getConstraintName ()
void setConstraintName (String constraintName)
String getTablespace ()
void setTablespace (String tablespace)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.AddUniqueConstraintChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 72 of file AddUniqueConstraintChange.java.
References liquibase.change.AddUniqueConstraintChange.getColumnNames(), liquibase.change.AddUniqueConstraintChange.getConstraintName(), liquibase.change.AddUniqueConstraintChange.getSchemaName(), liquibase.change.AddUniqueConstraintChange.getTableName(), liquibase.change.AddUniqueConstraintChange.getTablespace(), and liquibase.database.sql.AddUniqueConstraintStatement.setTablespace().
{
        AddUniqueConstraintStatement statement = new AddUniqueConstraintStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName(), getColumnNames(), getConstraintName());
        statement.setTablespace(getTablespace());
        return new SqlStatement[] { statement };
    }
String liquibase.change.AddUniqueConstraintChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 79 of file AddUniqueConstraintChange.java.
References liquibase.change.AddUniqueConstraintChange.getColumnNames(), and liquibase.change.AddUniqueConstraintChange.getTableName().
{
        return "Unique constraint added to "+getTableName()+"("+getColumnNames()+")";
    }
Element liquibase.change.AddUniqueConstraintChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 94 of file AddUniqueConstraintChange.java.
References liquibase.change.AddUniqueConstraintChange.getColumnNames(), liquibase.change.AddUniqueConstraintChange.getConstraintName(), liquibase.change.AddUniqueConstraintChange.getSchemaName(), liquibase.change.AddUniqueConstraintChange.getTableName(), liquibase.change.AddUniqueConstraintChange.getTablespace(), and liquibase.change.AbstractChange.getTagName().
{
        Element element = currentChangeLogFileDOM.createElement(getTagName());
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        if (getTablespace() != null) {
            element.setAttribute("tablespace", getTablespace());
        }
        element.setAttribute("tableName", getTableName());
        element.setAttribute("columnNames", getColumnNames());
        element.setAttribute("constraintName", getConstraintName());
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AddUniqueConstraintChange.java