LiquiBase: liquibase.change.DropForeignKeyConstraintChange Class Reference
liquibase.change.DropForeignKeyConstraintChange
liquibase.change.DropForeignKeyConstraintChange Class Reference
Detailed Description
Drops an existing foreign key constraint.
Definition at line 19 of file DropForeignKeyConstraintChange.java.
Public Member Functions
DropForeignKeyConstraintChange ()
String getBaseTableSchemaName ()
void setBaseTableSchemaName (String baseTableSchemaName)
String getBaseTableName ()
void setBaseTableName (String baseTableName)
String getConstraintName ()
void setConstraintName (String constraintName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.DropForeignKeyConstraintChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 52 of file DropForeignKeyConstraintChange.java.
References liquibase.change.DropForeignKeyConstraintChange.getBaseTableName(), liquibase.change.DropForeignKeyConstraintChange.getBaseTableSchemaName(), and liquibase.change.DropForeignKeyConstraintChange.getConstraintName().
{
        return new SqlStatement[]{
                new DropForeignKeyConstraintStatement(
                        getBaseTableSchemaName() == null?database.getDefaultSchemaName():getBaseTableSchemaName(),
                        getBaseTableName(),
                        getConstraintName()),
        };
    }
String liquibase.change.DropForeignKeyConstraintChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 61 of file DropForeignKeyConstraintChange.java.
References liquibase.change.DropForeignKeyConstraintChange.getConstraintName().
{
        return "Foreign key " + getConstraintName() + " dropped";
    }
Element liquibase.change.DropForeignKeyConstraintChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 65 of file DropForeignKeyConstraintChange.java.
References liquibase.change.DropForeignKeyConstraintChange.getBaseTableName(), liquibase.change.DropForeignKeyConstraintChange.getBaseTableSchemaName(), liquibase.change.DropForeignKeyConstraintChange.getConstraintName(), and liquibase.change.AbstractChange.getTagName().
{
        Element node = currentChangeLogFileDOM.createElement(getTagName());
        if (getBaseTableSchemaName() != null) {
            node.setAttribute("baseTableSchemaName", getBaseTableSchemaName());
        }
        node.setAttribute("baseTableName", getBaseTableName());
        node.setAttribute("constraintName", getConstraintName());
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DropForeignKeyConstraintChange.java