LiquiBase: liquibase.change.CreateViewChange Class Reference
liquibase.change.CreateViewChange
liquibase.change.CreateViewChange Class Reference
Detailed Description
Creats a new view.
Definition at line 19 of file CreateViewChange.java.
Public Member Functions
CreateViewChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getViewName ()
void setViewName (String viewName)
String getSelectQuery ()
void setSelectQuery (String selectQuery)
Boolean getReplaceIfExists ()
void setReplaceIfExists (Boolean replaceIfExists)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.CreateViewChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 62 of file CreateViewChange.java.
References liquibase.change.CreateViewChange.getReplaceIfExists(), liquibase.change.CreateViewChange.getSchemaName(), liquibase.change.CreateViewChange.getSelectQuery(), and liquibase.change.CreateViewChange.getViewName().
{
        boolean replaceIfExists = false;
        if (getReplaceIfExists() != null && getReplaceIfExists()) {
            replaceIfExists = true;
        }
        return new SqlStatement[]{
                new CreateViewStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getViewName(), getSelectQuery(), replaceIfExists),
        };
    }
String liquibase.change.CreateViewChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 72 of file CreateViewChange.java.
References liquibase.change.CreateViewChange.getViewName().
{
        return "View "+getViewName()+" created";
    }
Element liquibase.change.CreateViewChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 76 of file CreateViewChange.java.
References liquibase.change.CreateViewChange.getSchemaName(), liquibase.change.CreateViewChange.getSelectQuery(), and liquibase.change.CreateViewChange.getViewName().
{
        Element element = currentChangeLogFileDOM.createElement("createView");
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("viewName", getViewName());
        element.appendChild(currentChangeLogFileDOM.createTextNode(getSelectQuery()));
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/CreateViewChange.java