LiquiBase: liquibase.change.RenameViewChange Class Reference
liquibase.change.RenameViewChange
liquibase.change.RenameViewChange Class Reference
Detailed Description
Renames an existing view.
Definition at line 19 of file RenameViewChange.java.
Public Member Functions
RenameViewChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getOldViewName ()
void setOldViewName (String oldViewName)
String getNewViewName ()
void setNewViewName (String newViewName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.RenameViewChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 52 of file RenameViewChange.java.
References liquibase.change.RenameViewChange.getNewViewName(), liquibase.change.RenameViewChange.getOldViewName(), and liquibase.change.RenameViewChange.getSchemaName().
{
        return new SqlStatement[]{new RenameViewStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getOldViewName(), getNewViewName())};
    }
String liquibase.change.RenameViewChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 66 of file RenameViewChange.java.
{
        return "View " + oldViewName + " renamed to " + newViewName;
    }
Element liquibase.change.RenameViewChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 70 of file RenameViewChange.java.
References liquibase.change.RenameViewChange.getNewViewName(), liquibase.change.RenameViewChange.getOldViewName(), liquibase.change.RenameViewChange.getSchemaName(), and liquibase.change.AbstractChange.getTagName().
{
        Element element = currentChangeLogFileDOM.createElement(getTagName());
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("oldViewName", getOldViewName());
        element.setAttribute("newViewName", getNewViewName());
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/RenameViewChange.java