LiquiBase: liquibase.change.InsertDataChange Class Reference
liquibase.change.InsertDataChange
liquibase.change.InsertDataChange Class Reference
Detailed Description
Inserts data into an existing table.
Definition at line 17 of file InsertDataChange.java.
Public Member Functions
InsertDataChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
List< ColumnConfig > getColumns ()
void setColumns (List< ColumnConfig > columns)
void addColumn (ColumnConfig column)
void removeColumn (ColumnConfig column)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.InsertDataChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 60 of file InsertDataChange.java.
References liquibase.database.sql.InsertStatement.addColumnValue(), liquibase.change.InsertDataChange.getSchemaName(), and liquibase.change.InsertDataChange.getTableName().
{
        InsertStatement statement = new InsertStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName());
        for (ColumnConfig column : columns) {
            statement.addColumnValue(column.getName(), column.getValueObject());
        }
        return new SqlStatement[]{
                statement
        };
    }
String liquibase.change.InsertDataChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 73 of file InsertDataChange.java.
References liquibase.change.InsertDataChange.getTableName().
{
        return "New row inserted into " + getTableName();
    }
Element liquibase.change.InsertDataChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 77 of file InsertDataChange.java.
References liquibase.change.InsertDataChange.getColumns(), liquibase.change.InsertDataChange.getSchemaName(), and liquibase.change.InsertDataChange.getTableName().
{
        Element node = currentChangeLogFileDOM.createElement("insert");
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        for (ColumnConfig col : getColumns()) {
            Element subNode = col.createNode(currentChangeLogFileDOM);
            node.appendChild(subNode);
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/InsertDataChange.java