LiquiBase: liquibase.database.AbstractDatabase Class Reference
liquibase.database.AbstractDatabase
liquibase.database.AbstractDatabase Class Reference
Detailed Description
AbstractDatabase is extended by all supported databases as a facade to the underlying database.
The physical connection can be retrieved from the AbstractDatabase implementation, as well as any database-specific characteristics such as the datatype for "boolean" fields.
Definition at line 32 of file AbstractDatabase.java.
Public Member Functions
DatabaseConnection getConnection ()
void setConnection (Connection conn)
void setConnection (DatabaseConnection conn)
boolean getAutoCommitMode ()
Auto-commit mode to run in.
boolean supportsDDLInTransaction ()
By default databases should support DDL within a transaction.
String getDatabaseProductName ()
Returns the name of the database product according to the underlying database.
String getDatabaseProductName (Connection conn) throws JDBCException
String getDatabaseProductVersion () throws JDBCException
String getDriverName () throws JDBCException
String getConnectionURL () throws JDBCException
String getConnectionUsername () throws JDBCException
String getDefaultCatalogName () throws JDBCException
String getDefaultSchemaName ()
void setDefaultSchemaName (String schemaName) throws JDBCException
boolean supportsSequences ()
Does the database type support sequence.
boolean supportsAutoIncrement ()
void setCurrentDateTimeFunction (String function)
String getColumnType (String columnType, Boolean autoIncrement)
Returns the database-specific datatype for the given column configuration.
final String getColumnType (ColumnConfig columnConfig)
String getFalseBooleanValue ()
The database-specific value to use for "false" "boolean" columns.
String getTrueBooleanValue ()
The database-specific value to use for "true" "boolean" columns.
String getDateLiteral (String isoDate)
Return a date literal with the same value as a string formatted using ISO 8601.
String getDateLiteral (java.sql.Timestamp date)
String getDateLiteral (java.sql.Date date)
String getDateLiteral (java.sql.Time date)
String getDateLiteral (Date date)
String getDateType ()
Returns the actual database-specific data type to use a "date" (no time information) column.
String getTimeType ()
Returns the actual database-specific data type to use a "time" column.
String getLineComment ()
Returns database-specific line comment string.
String getAutoIncrementClause ()
Returns database-specific auto-increment DDL clause.
String getConcatSql (String...values)
Returns SQL to concat the passed values.
String getDatabaseChangeLogTableName ()
String getDatabaseChangeLogLockTableName ()
SqlStatement getSelectChangeLogLockSQL () throws JDBCException
boolean doesChangeLogTableExist ()
boolean doesChangeLogLockTableExist ()
void checkDatabaseChangeLogTable () throws JDBCException
This method will check the database ChangeLog table used to keep track of the changes in the file.
void checkDatabaseChangeLogLockTable () throws JDBCException
This method will check the database ChangeLogLock table used to keep track of if a machine is updating the database.
void dropDatabaseObjects (String schema) throws JDBCException
Drops all objects owned by the connected user.
boolean isSystemTable (String catalogName, String schemaName, String tableName)
boolean isSystemView (String catalogName, String schemaName, String viewName)
boolean isLiquibaseTable (String tableName)
void tag (String tagString) throws JDBCException
Tags the database changelog with the given string.
SqlStatement createFindSequencesSQL (String schema) throws JDBCException
boolean doesTagExist (String tag) throws JDBCException
DatabaseSnapshot getSnapshot () throws JDBCException
String toString ()
boolean shouldQuoteValue (String value)
String getViewDefinition (String schemaName, String viewName) throws JDBCException
SqlStatement getViewDefinitionSql (String schemaName, String viewName) throws JDBCException
int getDatabaseType (int type)
Object convertDatabaseValueToJavaObject (Object defaultValue, int dataType, int columnSize, int decimalDigits) throws ParseException
String convertJavaObjectToString (Object value)
String escapeTableName (String schemaName, String tableName)
Escapes the table name in a database-dependent manner so reserved words can be used as a table name (i.e.
String escapeSequenceName (String schemaName, String sequenceName)
String convertRequestedSchemaToCatalog (String requestedSchema) throws JDBCException
String convertRequestedSchemaToSchema (String requestedSchema) throws JDBCException
boolean supportsSchemas ()
String generatePrimaryKeyName (String tableName)
String escapeViewName (String schemaName, String viewName)
boolean isColumnAutoIncrement (String schemaName, String tableName, String columnName) throws SQLException, JDBCException
ChangeSet.RunStatus getRunStatus (ChangeSet changeSet) throws JDBCException, DatabaseHistoryException
Returns the run status for the given ChangeSet.
RanChangeSet getRanChangeSet (ChangeSet changeSet) throws JDBCException, DatabaseHistoryException
List< RanChangeSet > getRanChangeSetList () throws JDBCException
Returns the ChangeSets that have been run against the current database.
Date getRanDate (ChangeSet changeSet) throws JDBCException, DatabaseHistoryException
void markChangeSetAsRan (ChangeSet changeSet) throws JDBCException
After the change set has been ran against the database this method will update the change log table with the information.
void markChangeSetAsReRan (ChangeSet changeSet) throws JDBCException
void removeRanStatus (ChangeSet changeSet) throws JDBCException
String escapeStringForDatabase (String string)
void commit () throws JDBCException
void rollback () throws JDBCException
JdbcTemplate getJdbcTemplate ()
void setJdbcTemplate (JdbcTemplate template)
boolean equals (Object o)
int hashCode ()
void close () throws JDBCException
Protected Member Functions
AbstractDatabase ()
String getDefaultDatabaseSchemaName () throws JDBCException
Set< String > getSystemTablesAndViews ()
Returns system (undroppable) tables and views.
Date parseDate (String dateAsString) throws DateParseException
boolean isDateOnly (String isoDate)
boolean isDateTime (String isoDate)
boolean isTimeOnly (String isoDate)
SqlStatement getCreateChangeLogLockSQL ()
SqlStatement getCreateChangeLogSQL ()
boolean canCreateChangeLogTable () throws JDBCException
SqlStatement createChangeToTagSQL ()
Returns SQL to return the date of the most recient changeset execution.
SqlStatement createTagSQL (String tagName, Date dateExecuted)
Returns SQL to tag the database.
Object convertToCorrectJavaType (String value, int dataType, int columnSize, int decimalDigits) throws ParseException
Protected Attributes
boolean changeLogTableExists
boolean changeLogLockTableExists
boolean changeLogCreateAttempted
boolean changeLogLockCreateAttempted
String currentDateTimeFunction
Static Protected Attributes
static final Logger log = LogFactory.getLogger()
Member Function Documentation
String liquibase.database.AbstractDatabase.getColumnType (String columnType, Boolean autoIncrement)
Returns the database-specific datatype for the given column configuration.
This method will convert some generic column types (e.g. boolean, currency) to the correct type for the current database.
Implements liquibase.database.Database.
Reimplemented in liquibase.database.FirebirdDatabase, liquibase.database.MSSQLDatabase, liquibase.database.OracleDatabase, and liquibase.database.PostgresDatabase.
Definition at line 189 of file AbstractDatabase.java.
References liquibase.database.Database.getBlobType(), liquibase.database.Database.getBooleanType(), liquibase.database.Database.getClobType(), liquibase.database.AbstractDatabase.getConnection(), liquibase.database.Database.getCurrencyType(), liquibase.database.Database.getDateTimeType(), liquibase.database.AbstractDatabase.getDateType(), liquibase.database.DatabaseConnection.getMetaData(), liquibase.database.AbstractDatabase.getTimeType(), and liquibase.database.Database.getUUIDType().
Referenced by liquibase.database.AbstractDatabase.getColumnType().
{
        if (columnType.startsWith("java.sql.Types")) {
            String dataTypeName = columnType.substring(columnType.lastIndexOf(".") + 1);
            String precision = null;
            if (dataTypeName.indexOf("(") >= 0) {
                precision = dataTypeName.substring(dataTypeName.indexOf("(") + 1, dataTypeName.indexOf(")"));
                dataTypeName = dataTypeName.substring(0, dataTypeName.indexOf("("));
            }
            ResultSet resultSet = null;
            try {
                DatabaseConnection connection = getConnection();
                if (connection == null) {
                    throw new RuntimeException("Cannot evaluate java.sql.Types without a connection");
                }
                resultSet = connection.getMetaData().getTypeInfo();
                while (resultSet.next()) {
                    String typeName = resultSet.getString("TYPE_NAME");
                    int dataType = resultSet.getInt("DATA_TYPE");
                    Integer requestedType = (Integer) Class.forName("java.sql.Types").getDeclaredField(dataTypeName).get(null);
                    if (requestedType == dataType) {
                        if (precision == null) {
                            return typeName;
                        } else {
                            return typeName + "(" + precision + ")";
                        }
                    }
                }
                //did not find type, fall back on our defaults for ones we can figure out
                if (dataTypeName.equalsIgnoreCase("BLOB")) {
                    return getBlobType();
                } else if (dataTypeName.equalsIgnoreCase("CLOB")) {
                    return getClobType();
                } else if (dataTypeName.equalsIgnoreCase("BOOLEAN")) {
                    return getBooleanType();
                } else if (dataTypeName.equalsIgnoreCase("DATE")) {
                    return getDateType();
                } else if (dataTypeName.equalsIgnoreCase("TIME")) {
                    return getTimeType();
                }
                throw new RuntimeException("Could not find java.sql.Types value for " + dataTypeName);
            } catch (Exception e) {
                throw new RuntimeException(e);
            } finally {
                if (resultSet != null) {
                    try {
                        resultSet.close();
                    } catch (SQLException e) {
                        ;
                    }
                }
            }
        } else if ("boolean".equalsIgnoreCase(columnType)) {
            return getBooleanType();
        } else if ("currency".equalsIgnoreCase(columnType)) {
            return getCurrencyType();
        } else if ("UUID".equalsIgnoreCase(columnType)) {
            return getUUIDType();
        } else if ("BLOB".equalsIgnoreCase(columnType)
                || "LONGVARBINARY".equalsIgnoreCase(columnType)) {
            return getBlobType();
        } else if ("CLOB".equalsIgnoreCase(columnType)
                || "TEXT".equalsIgnoreCase(columnType)
                || "LONGVARCHAR".equalsIgnoreCase(columnType)) {
            return getClobType();
        } else if ("date".equalsIgnoreCase(columnType)) {
            return getDateType();
        } else if ("time".equalsIgnoreCase(columnType)) {
            return getTimeType();
        } else if ("dateTime".equalsIgnoreCase(columnType)) {
            return getDateTimeType();
        } else if (columnType.toUpperCase().startsWith("FLOAT(")) {
            return "FLOAT";
        } else if (columnType.toUpperCase().startsWith("DOUBLE(")) {
            return "DOUBLE";
        } else {
            return columnType;
        }
    }
String liquibase.database.AbstractDatabase.getDateLiteral (String isoDate)
Return a date literal with the same value as a string formatted using ISO 8601.
Note: many databases accept date literals in ISO8601 format with the 'T' replaced with a space. Only databases which do not accept these strings should need to override this method.
Implementation restriction: Currently, only the following subsets of ISO8601 are supported: yyyy-MM-dd hh:mm:ss yyyy-MM-ddThh:mm:ss
Implements liquibase.database.Database.
Reimplemented in liquibase.database.DB2Database, liquibase.database.DerbyDatabase, liquibase.database.HsqlDatabase, and liquibase.database.OracleDatabase.
Definition at line 301 of file AbstractDatabase.java.
References liquibase.database.AbstractDatabase.isDateOnly(), liquibase.database.AbstractDatabase.isDateTime(), and liquibase.database.AbstractDatabase.isTimeOnly().
Referenced by liquibase.database.AbstractDatabase.getDateLiteral().
{
        if (isDateOnly(isoDate) || isTimeOnly(isoDate)) {
            return "'" + isoDate + "'";
        } else if (isDateTime(isoDate)) {
            StringBuffer val = new StringBuffer();
            val.append("'");
            val.append(isoDate.substring(0, 10));
            val.append(" ");
//noinspection MagicNumber
            val.append(isoDate.substring(11));
            val.append("'");
            return val.toString();
        } else {
            return "BAD_DATE_FORMAT:" + isoDate;
        }
    }
void liquibase.database.AbstractDatabase.checkDatabaseChangeLogTable () throws JDBCException
This method will check the database ChangeLog table used to keep track of the changes in the file.
If the table does not exist it will create one otherwise it will not do anything besides outputting a log message.
Implements liquibase.database.Database.
Definition at line 464 of file AbstractDatabase.java.
References liquibase.database.AbstractDatabase.canCreateChangeLogTable(), liquibase.database.AbstractDatabase.changeLogCreateAttempted, liquibase.database.AbstractDatabase.changeLogTableExists, liquibase.database.template.JdbcTemplate.comment(), liquibase.database.AbstractDatabase.convertRequestedSchemaToCatalog(), liquibase.database.AbstractDatabase.convertRequestedSchemaToSchema(), liquibase.database.AbstractDatabase.escapeTableName(), liquibase.database.AbstractDatabase.getConnection(), liquibase.database.AbstractDatabase.getCreateChangeLogSQL(), liquibase.database.AbstractDatabase.getDatabaseChangeLogTableName(), liquibase.database.AbstractDatabase.getDefaultSchemaName(), liquibase.database.AbstractDatabase.getJdbcTemplate(), liquibase.database.DatabaseConnection.getMetaData(), and liquibase.database.AbstractDatabase.log.
{
        DatabaseConnection connection = getConnection();
        ResultSet checkTableRS = null;
        ResultSet checkColumnsRS = null;
        List<SqlStatement> statementsToExecute = new ArrayList<SqlStatement>();
        try {
            checkTableRS = connection.getMetaData().getTables(convertRequestedSchemaToCatalog(getDefaultSchemaName()), convertRequestedSchemaToSchema(getDefaultSchemaName()), getDatabaseChangeLogTableName(), new String[]{"TABLE"});
            if (checkTableRS.next()) {
                changeLogTableExists = true;
                checkColumnsRS = connection.getMetaData().getColumns(convertRequestedSchemaToCatalog(getDefaultSchemaName()), convertRequestedSchemaToSchema(getDefaultSchemaName()), getDatabaseChangeLogTableName(), null);
                boolean hasDescription = false;
                boolean hasComments = false;
                boolean hasTag = false;
                boolean hasLiquibase = false;
                while (checkColumnsRS.next()) {
                    String columnName = checkColumnsRS.getString("COLUMN_NAME");
                    if ("DESCRIPTION".equalsIgnoreCase(columnName)) {
                        hasDescription = true;
                    } else if ("COMMENTS".equalsIgnoreCase(columnName)) {
                        hasComments = true;
                    } else if ("TAG".equalsIgnoreCase(columnName)) {
                        hasTag = true;
                    } else if ("LIQUIBASE".equalsIgnoreCase(columnName)) {
                        hasLiquibase = true;
                    }
                }
                if (!hasDescription) {
                    statementsToExecute.add(new AddColumnStatement(getDefaultSchemaName(), getDatabaseChangeLogTableName(), "DESCRIPTION", "VARCHAR(255)", null));
                }
                if (!hasTag) {
                    statementsToExecute.add(new AddColumnStatement(getDefaultSchemaName(), getDatabaseChangeLogTableName(), "TAG", "VARCHAR(255)", null));
                }
                if (!hasComments) {
                    statementsToExecute.add(new AddColumnStatement(getDefaultSchemaName(), getDatabaseChangeLogTableName(), "COMMENTS", "VARCHAR(255)", null));
                }
                if (!hasLiquibase) {
                    statementsToExecute.add(new AddColumnStatement(getDefaultSchemaName(), getDatabaseChangeLogTableName(), "LIQUIBASE", "VARCHAR(255)", null));
                }
            } else if (!changeLogCreateAttempted) {
                changeLogCreateAttempted = true;
                getJdbcTemplate().comment("Create Database Change Log Table");
                SqlStatement createTableStatement = getCreateChangeLogSQL();
                if (!canCreateChangeLogTable()) {
                    throw new JDBCException("Cannot create " + escapeTableName(getDefaultSchemaName(), getDatabaseChangeLogTableName()) + " table for your database.\n\n" +
                            "Please construct it manually using the following SQL as a base and re-run LiquiBase:\n\n" +
                            createTableStatement);
                }
                // If there is no table in the database for recording change history create one.
                statementsToExecute.add(createTableStatement);
                log.info("Creating database history table with name: " + escapeTableName(getDefaultSchemaName(), getDatabaseChangeLogTableName()));
                changeLogTableExists = true;
//                }
            }
            for (SqlStatement sql : statementsToExecute) {
                this.getJdbcTemplate().execute(sql);
                this.commit();
            }
        } catch (SQLException e) {
            throw new JDBCException(e);
        } finally {
            if (checkTableRS != null) {
                try {
                    checkTableRS.close();
                } catch (SQLException e) {
                    //noinspection ThrowFromFinallyBlock
                    throw new JDBCException(e);
                }
            }
            if (checkColumnsRS != null) {
                try {
                    checkColumnsRS.close();
                } catch (SQLException e) {
                    //noinspection ThrowFromFinallyBlock
                    throw new JDBCException(e);
                }
            }
        }
    }
void liquibase.database.AbstractDatabase.checkDatabaseChangeLogLockTable () throws JDBCException
This method will check the database ChangeLogLock table used to keep track of if a machine is updating the database.
If the table does not exist it will create one otherwise it will not do anything besides outputting a log message.
Implements liquibase.database.Database.
Definition at line 556 of file AbstractDatabase.java.
References liquibase.database.AbstractDatabase.changeLogLockCreateAttempted, liquibase.database.AbstractDatabase.changeLogLockTableExists, liquibase.database.template.JdbcTemplate.comment(), liquibase.database.AbstractDatabase.convertRequestedSchemaToCatalog(), liquibase.database.AbstractDatabase.convertRequestedSchemaToSchema(), liquibase.database.AbstractDatabase.escapeTableName(), liquibase.database.AbstractDatabase.getConnection(), liquibase.database.AbstractDatabase.getCreateChangeLogLockSQL(), liquibase.database.AbstractDatabase.getDatabaseChangeLogLockTableName(), liquibase.database.AbstractDatabase.getDefaultSchemaName(), liquibase.database.AbstractDatabase.getJdbcTemplate(), liquibase.database.DatabaseConnection.getMetaData(), and liquibase.database.AbstractDatabase.log.
{
        DatabaseConnection connection = getConnection();
        ResultSet rs = null;
        boolean knowMustInsertIntoLockTable = false;
        try {
            rs = connection.getMetaData().getTables(convertRequestedSchemaToCatalog(getDefaultSchemaName()), convertRequestedSchemaToSchema(getDefaultSchemaName()), getDatabaseChangeLogLockTableName(), new String[]{"TABLE"});
            if (!rs.next()) {
                if (!changeLogLockCreateAttempted) {
                    changeLogLockCreateAttempted = true;
                    SqlStatement createTableStatement = getCreateChangeLogLockSQL();
                    getJdbcTemplate().comment("Create Database Lock Table");
                    this.getJdbcTemplate().execute(createTableStatement);
                    this.commit();
                    log.info("Created database lock table with name: " + escapeTableName(getDefaultSchemaName(), getDatabaseChangeLogLockTableName()));
                    changeLogLockTableExists = true;
                    knowMustInsertIntoLockTable = true;
                }
            } else {
                changeLogLockTableExists = true;
            }
            rs.close();
            if (changeLogLockTableExists) {
                int rows = -1;
                if (!knowMustInsertIntoLockTable) {
                    RawSqlStatement selectStatement = new RawSqlStatement("SELECT COUNT(*) FROM " + escapeTableName(getDefaultSchemaName(), getDatabaseChangeLogLockTableName()) + " WHERE ID=1");
                    rows = this.getJdbcTemplate().queryForInt(selectStatement);
                }
                if (knowMustInsertIntoLockTable || rows == 0) {
                    this.getJdbcTemplate().update(getChangeLogLockInsertSQL());
                    this.commit();
                    log.info("Inserted lock row into: " + escapeTableName(getDefaultSchemaName(), getDatabaseChangeLogLockTableName()));
                    rs.close();
                }
            } else {
                throw new JDBCException("Change log lock table does not exist");
            }
        } catch (SQLException e) {
            throw new JDBCException(e);
        } finally {
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException e) {
                    //noinspection ThrowFromFinallyBlock
                    throw new JDBCException(e);
                }
            }
        }
    }
void liquibase.database.AbstractDatabase.dropDatabaseObjects (String schema) throws JDBCException
Drops all objects owned by the connected user.
Parameters:
schema
Implements liquibase.database.Database.
Definition at line 616 of file AbstractDatabase.java.
References liquibase.database.AbstractDatabase.changeLogTableExists, liquibase.database.AbstractDatabase.convertRequestedSchemaToSchema(), liquibase.database.AbstractDatabase.escapeTableName(), liquibase.database.AbstractDatabase.getDatabaseChangeLogTableName(), liquibase.database.AbstractDatabase.getDefaultSchemaName(), liquibase.database.structure.DatabaseSnapshot.getForeignKeys(), liquibase.database.structure.DatabaseSnapshot.getSequences(), liquibase.database.structure.DatabaseSnapshot.getTables(), liquibase.database.structure.DatabaseSnapshot.getViews(), liquibase.change.DropForeignKeyConstraintChange.setBaseTableName(), liquibase.change.DropForeignKeyConstraintChange.setBaseTableSchemaName(), liquibase.change.DropForeignKeyConstraintChange.setConstraintName(), liquibase.change.DropSequenceChange.setSchemaName(), liquibase.change.DropTableChange.setSchemaName(), liquibase.change.DropViewChange.setSchemaName(), liquibase.change.DropSequenceChange.setSequenceName(), liquibase.change.AbstractSQLChange.setSql(), liquibase.change.DropTableChange.setTableName(), liquibase.change.DropViewChange.setViewName(), and liquibase.database.AbstractDatabase.supportsSequences().
{
        try {
            DatabaseSnapshot snapshot = new DatabaseSnapshot(this, new HashSet<DiffStatusListener>(), schema);
            List<Change> dropChanges = new ArrayList<Change>();
            for (ForeignKey fk : snapshot.getForeignKeys()) {
                DropForeignKeyConstraintChange dropFK = new DropForeignKeyConstraintChange();
                dropFK.setBaseTableSchemaName(schema);
                dropFK.setBaseTableName(fk.getForeignKeyTable().getName());
                dropFK.setConstraintName(fk.getName());
                dropChanges.add(dropFK);
            }
            for (View view : snapshot.getViews()) {
                DropViewChange dropChange = new DropViewChange();
                dropChange.setViewName(view.getName());
                dropChange.setSchemaName(schema);
                dropChanges.add(dropChange);
            }
//            for (Index index : snapshot.getIndexes()) {
//                DropIndexChange dropChange = new DropIndexChange();
//                dropChange.setIndexName(index.getName());
//                dropChange.setSchemaName(schema);
//                dropChange.setTableName(index.getTableName());
//
//                dropChanges.add(dropChange);
//            }
            for (Table table : snapshot.getTables()) {
                DropTableChange dropChange = new DropTableChange();
                dropChange.setSchemaName(schema);
                dropChange.setTableName(table.getName());
                dropChanges.add(dropChange);
            }
            if (this.supportsSequences()) {
                for (Sequence seq : snapshot.getSequences()) {
                    DropSequenceChange dropChange = new DropSequenceChange();
                    dropChange.setSequenceName(seq.getName());
                    dropChange.setSchemaName(schema);
                    dropChanges.add(dropChange);
                }
            }
            if (this.changeLogTableExists) {
                RawSQLChange clearChangeLogChange = new RawSQLChange();
                clearChangeLogChange.setSql("DELETE FROM " + escapeTableName(convertRequestedSchemaToSchema(getDefaultSchemaName()), getDatabaseChangeLogTableName()));
                dropChanges.add(clearChangeLogChange);
            }
            try {
                for (Change change : dropChanges) {
                    for (SqlStatement statement : change.generateStatements(this)) {
                        this.getJdbcTemplate().execute(statement);
                    }
                }
            } catch (UnsupportedChangeException e) {
                throw new JDBCException(e);
            }
        } finally {
            this.commit();
        }
    }
SqlStatement liquibase.database.AbstractDatabase.createTagSQL (String tagName, Date dateExecuted) [protected]
Returns SQL to tag the database.
SQL Contains two ?:
tag string
date executed
Definition at line 749 of file AbstractDatabase.java.
References liquibase.database.sql.UpdateStatement.addNewColumnValue(), liquibase.database.sql.UpdateStatement.addWhereParameter(), liquibase.database.AbstractDatabase.getDatabaseChangeLogTableName(), liquibase.database.AbstractDatabase.getDefaultSchemaName(), and liquibase.database.sql.UpdateStatement.setWhereClause().
Referenced by liquibase.database.AbstractDatabase.tag().
{
        UpdateStatement statement = new UpdateStatement(getDefaultSchemaName(), getDatabaseChangeLogTableName());
        statement.addNewColumnValue("TAG", tagName);
        statement.setWhereClause("DATEEXECUTED = ?");
        statement.addWhereParameter(dateExecuted);
        return statement;
    }
String liquibase.database.AbstractDatabase.escapeTableName (String schemaName, String tableName)
Escapes the table name in a database-dependent manner so reserved words can be used as a table name (i.e.
"order"). Currently only escapes MS-SQL because other DBMSs store table names case-sensitively when escaping is used which could confuse end-users. Pass null to schemaName to use the default schema
Implements liquibase.database.Database.
Reimplemented in liquibase.database.MSSQLDatabase.
Definition at line 941 of file AbstractDatabase.java.
References liquibase.database.AbstractDatabase.supportsSchemas().
Referenced by liquibase.database.AbstractDatabase.checkDatabaseChangeLogLockTable(), liquibase.database.AbstractDatabase.checkDatabaseChangeLogTable(), liquibase.database.AbstractDatabase.createChangeToTagSQL(), liquibase.database.AbstractDatabase.doesTagExist(), liquibase.database.AbstractDatabase.dropDatabaseObjects(), liquibase.database.AbstractDatabase.escapeViewName(), liquibase.database.AbstractDatabase.getRanChangeSetList(), liquibase.database.AbstractDatabase.getRunStatus(), liquibase.database.AbstractDatabase.getSelectChangeLogLockSQL(), liquibase.database.AbstractDatabase.isColumnAutoIncrement(), and liquibase.database.AbstractDatabase.tag().
{
        if (StringUtils.trimToNull(schemaName) == null || !supportsSchemas()) {
            return tableName;
        } else {
            return schemaName + "." + tableName;
        }
    }
The documentation for this class was generated from the following file:
java/liquibase/database/AbstractDatabase.java