LiquiBase: liquibase.change.DropIndexChange Class Reference
liquibase.change.DropIndexChange
liquibase.change.DropIndexChange Class Reference
Detailed Description
Drops an existing index.
Definition at line 20 of file DropIndexChange.java.
Public Member Functions
DropIndexChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getIndexName ()
void setIndexName (String indexName)
String getTableName ()
void setTableName (String tableName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.DropIndexChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 54 of file DropIndexChange.java.
References liquibase.change.DropIndexChange.getIndexName(), liquibase.change.DropIndexChange.getSchemaName(), and liquibase.change.DropIndexChange.getTableName().
{
        return new SqlStatement[] {
            new DropIndexStatement(getIndexName(), getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName())
        };
    }
String liquibase.change.DropIndexChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 60 of file DropIndexChange.java.
References liquibase.change.DropIndexChange.getIndexName(), and liquibase.change.DropIndexChange.getTableName().
{
        return "Index " + getIndexName() + " dropped from table " + getTableName();
    }
Element liquibase.change.DropIndexChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 64 of file DropIndexChange.java.
References liquibase.change.DropIndexChange.getIndexName(), liquibase.change.DropIndexChange.getSchemaName(), and liquibase.change.DropIndexChange.getTableName().
{
        Element element = currentChangeLogFileDOM.createElement("dropIndex");
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("indexName", getIndexName());
        element.setAttribute("tableName", getTableName());
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DropIndexChange.java