LiquiBase: liquibase.database.DB2Database Class Reference
liquibase.database.DB2Database
liquibase.database.DB2Database Class Reference
Detailed Description
Definition at line 12 of file DB2Database.java.
Public Member Functions
boolean isCorrectDatabaseImplementation (Connection conn) throws JDBCException
Is this AbstractDatabase subclass the correct one to use for the given connection.
String getDefaultDriver (String url)
If this database understands the given url, return the default driver class name.
String getProductName ()
Returns the full database product name.
String getTypeName ()
Returns an all-lower-case short name of the product.
boolean supportsInitiallyDeferrableColumns ()
Returns whether this database support initially deferrable columns.
String getAutoIncrementClause ()
Returns database-specific auto-increment DDL clause.
String getCurrentDateTimeFunction ()
Returns database-specific function for generating the current date/time.
String getBooleanType ()
Returns the actual database-specific data type to use a "boolean" column.
String getTrueBooleanValue ()
The database-specific value to use for "true" "boolean" columns.
String getFalseBooleanValue ()
The database-specific value to use for "false" "boolean" columns.
String getDateLiteral (String isoDate)
Return an DB2 date literal with the same value as a string formatted using ISO 8601.
String getCurrencyType ()
Returns the actual database-specific data type to use a "currency" column.
String getUUIDType ()
Returns the actual database-specific data type to use a "UUID" column.
String getClobType ()
Returns the actual database-specific data type to use a "CLOB" column.
String getBlobType ()
Returns the actual database-specific data type to use a "BLOB" column.
String getDateTimeType ()
Returns the actual database-specific data type to use a "datetime" column.
SqlStatement createFindSequencesSQL (String schema) throws JDBCException
boolean shouldQuoteValue (String value)
boolean supportsTablespaces ()
SqlStatement getViewDefinitionSql (String schemaName, String name) throws JDBCException
String getViewDefinition (String schemaName, String name) throws JDBCException
Object convertDatabaseValueToJavaObject (Object defaultValue, int dataType, int columnSize, int decimalDigits) throws ParseException
String convertRequestedSchemaToSchema (String requestedSchema) throws JDBCException
String convertRequestedSchemaToCatalog (String requestedSchema) throws JDBCException
String generatePrimaryKeyName (String tableName)
boolean isColumnAutoIncrement (String schemaName, String tableName, String columnName) throws SQLException, JDBCException
Protected Member Functions
String getDefaultDatabaseSchemaName () throws JDBCException
java.util.Date parseDate (String dateAsString) throws DateParseException
Member Function Documentation
String liquibase.database.DB2Database.getDefaultDriver (String url)
If this database understands the given url, return the default driver class name.
Otherwise return null.
Implements liquibase.database.Database.
Definition at line 17 of file DB2Database.java.
{
        if (url.startsWith("jdbc:db2")) {
            return "com.ibm.db2.jcc.DB2Driver";
        }
        return null;
    }
String liquibase.database.DB2Database.getProductName ()
Returns the full database product name.
May be different than what the JDBC connection reports (getDatabaseProductName())
Implements liquibase.database.Database.
Definition at line 24 of file DB2Database.java.
{
        return "DB2";
    }
String liquibase.database.DB2Database.getTypeName ()
Returns an all-lower-case short name of the product.
Used for end-user selecting of database type such as the DBMS precondition.
Implements liquibase.database.Database.
Definition at line 28 of file DB2Database.java.
{
        return "db2";
    }
String liquibase.database.DB2Database.getDateLiteral (String isoDate)
Return an DB2 date literal with the same value as a string formatted using ISO 8601.
Convert an ISO8601 date string to one of the following results: to_date('1995-05-23', 'YYYY-MM-DD') to_date('1995-05-23 09:23:59', 'YYYY-MM-DD HH24:MI:SS')
Implementation restriction: Currently, only the following subsets of ISO8601 are supported: YYYY-MM-DD hh:mm:ss YYYY-MM-DDThh:mm:ss
Reimplemented from liquibase.database.AbstractDatabase.
Definition at line 73 of file DB2Database.java.
References liquibase.database.AbstractDatabase.isDateOnly(), liquibase.database.AbstractDatabase.isDateTime(), and liquibase.database.AbstractDatabase.isTimeOnly().
{
        String normalLiteral = super.getDateLiteral(isoDate);
        if (isDateOnly(isoDate)) {
            StringBuffer val = new StringBuffer();
            val.append("DATE(");
            val.append(normalLiteral);
            val.append(')');
            return val.toString();
        } else if (isTimeOnly(isoDate)) {
            StringBuffer val = new StringBuffer();
            val.append("TIME(");
            val.append(normalLiteral);
            val.append(')');
            return val.toString();
        } else if (isDateTime(isoDate)) {
            StringBuffer val = new StringBuffer();
            val.append("TIMESTAMP(");
            val.append(normalLiteral);
            val.append(')');
            return val.toString();
        } else {
            return "UNSUPPORTED:" + isoDate;
        }
    }
The documentation for this class was generated from the following file:
java/liquibase/database/DB2Database.java