LiquiBase: liquibase.change.AddPrimaryKeyChange Class Reference
liquibase.change.AddPrimaryKeyChange
liquibase.change.AddPrimaryKeyChange Class Reference
Detailed Description
Creates a primary key out of an existing column or set of columns.
Definition at line 21 of file AddPrimaryKeyChange.java.
Public Member Functions
AddPrimaryKeyChange ()
String getTableName ()
void setTableName (String tableName)
String getSchemaName ()
void setSchemaName (String schemaName)
String getColumnNames ()
void setColumnNames (String columnNames)
String getConstraintName ()
void setConstraintName (String constraintName)
String getTablespace ()
void setTablespace (String tablespace)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.AddPrimaryKeyChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 74 of file AddPrimaryKeyChange.java.
References liquibase.change.AddPrimaryKeyChange.getColumnNames(), liquibase.change.AddPrimaryKeyChange.getConstraintName(), liquibase.change.AddPrimaryKeyChange.getSchemaName(), liquibase.change.AddPrimaryKeyChange.getTableName(), liquibase.change.AddPrimaryKeyChange.getTablespace(), and liquibase.database.sql.AddPrimaryKeyStatement.setTablespace().
Referenced by liquibase.change.AddLookupTableChange.generateStatements(), and liquibase.change.AddColumnChange.generateStatements().
{
        String schemaName = getSchemaName() == null?database.getDefaultSchemaName():getSchemaName();
        AddPrimaryKeyStatement statement = new AddPrimaryKeyStatement(schemaName, getTableName(), getColumnNames(), getConstraintName());
        statement.setTablespace(getTablespace());
        if (database instanceof DB2Database) {
            return new SqlStatement[]{
                    statement,
                    new ReorganizeTableStatement(schemaName, getTableName())
            };
        }
        return new SqlStatement[]{
                statement
        };
    }
String liquibase.change.AddPrimaryKeyChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 103 of file AddPrimaryKeyChange.java.
References liquibase.change.AddPrimaryKeyChange.getColumnNames(), and liquibase.change.AddPrimaryKeyChange.getTableName().
{
        return "Primary key added to " + getTableName() + " (" + getColumnNames() + ")";
    }
Element liquibase.change.AddPrimaryKeyChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 107 of file AddPrimaryKeyChange.java.
References liquibase.change.AddPrimaryKeyChange.getColumnNames(), liquibase.change.AddPrimaryKeyChange.getConstraintName(), liquibase.change.AddPrimaryKeyChange.getSchemaName(), liquibase.change.AddPrimaryKeyChange.getTableName(), liquibase.change.AddPrimaryKeyChange.getTablespace(), and liquibase.change.AbstractChange.getTagName().
{
        Element node = currentChangeLogFileDOM.createElement(getTagName());
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        node.setAttribute("columnNames", getColumnNames());
        if (getConstraintName() != null) {
            node.setAttribute("constraintName", getConstraintName());
        }
        if (getTablespace() != null) {
            node.setAttribute("tablespace", getTablespace());
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/AddPrimaryKeyChange.java