LiquiBase: liquibase.change.RenameTableChange Class Reference
liquibase.change.RenameTableChange
liquibase.change.RenameTableChange Class Reference
Detailed Description
Renames an existing table.
Definition at line 19 of file RenameTableChange.java.
Public Member Functions
RenameTableChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getOldTableName ()
void setOldTableName (String oldTableName)
String getNewTableName ()
void setNewTableName (String newTableName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.RenameTableChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 55 of file RenameTableChange.java.
References liquibase.change.RenameTableChange.getNewTableName(), liquibase.change.RenameTableChange.getOldTableName(), and liquibase.change.RenameTableChange.getSchemaName().
{
        List<SqlStatement> statements = new ArrayList<SqlStatement>();
        String schemaName = getSchemaName() == null?database.getDefaultSchemaName():getSchemaName();
        statements.add(new RenameTableStatement(schemaName, getOldTableName(), getNewTableName()));
        if (database instanceof DB2Database) {
            statements.add(new ReorganizeTableStatement(schemaName, getNewTableName()));
        }
        return statements.toArray(new SqlStatement[statements.size()]);
    }
String liquibase.change.RenameTableChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 77 of file RenameTableChange.java.
{
        return "Table " + oldTableName + " renamed to " + newTableName;
    }
Element liquibase.change.RenameTableChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 81 of file RenameTableChange.java.
References liquibase.change.RenameTableChange.getNewTableName(), liquibase.change.RenameTableChange.getOldTableName(), and liquibase.change.RenameTableChange.getSchemaName().
{
        Element element = currentChangeLogFileDOM.createElement("renameTable");
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("oldTableName", getOldTableName());
        element.setAttribute("newTableName", getNewTableName());
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/RenameTableChange.java