LiquiBase: liquibase.change.DropPrimaryKeyChange Class Reference
liquibase.change.DropPrimaryKeyChange
liquibase.change.DropPrimaryKeyChange Class Reference
Detailed Description
Removes an existing primary key.
Definition at line 18 of file DropPrimaryKeyChange.java.
Public Member Functions
DropPrimaryKeyChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getConstraintName ()
void setConstraintName (String constraintName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.DropPrimaryKeyChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 51 of file DropPrimaryKeyChange.java.
References liquibase.change.DropPrimaryKeyChange.getConstraintName(), liquibase.change.DropPrimaryKeyChange.getSchemaName(), and liquibase.change.DropPrimaryKeyChange.getTableName().
{
        return new SqlStatement[]{
                new DropPrimaryKeyStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName(), getConstraintName()),
        };
    }
String liquibase.change.DropPrimaryKeyChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 57 of file DropPrimaryKeyChange.java.
References liquibase.change.DropPrimaryKeyChange.getTableName().
{
        return "Primary key dropped from "+getTableName();
    }
Element liquibase.change.DropPrimaryKeyChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 61 of file DropPrimaryKeyChange.java.
References liquibase.change.DropPrimaryKeyChange.getConstraintName(), liquibase.change.DropPrimaryKeyChange.getSchemaName(), liquibase.change.DropPrimaryKeyChange.getTableName(), and liquibase.change.AbstractChange.getTagName().
{
        Element node = currentChangeLogFileDOM.createElement(getTagName());
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        if (getConstraintName() != null) {
            node.setAttribute("constraintName", getConstraintName());
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DropPrimaryKeyChange.java