LiquiBase: liquibase.util.StringUtils Class Reference
liquibase.util.StringUtils
liquibase.util.StringUtils Class Reference
Detailed Description
Various utility methods for working with strings.
Definition at line 10 of file StringUtils.java.
Static Public Member Functions
static String trimToEmpty (String string)
static String trimToNull (String string)
static String[] processMutliLineSQL (String multiLineSQL, boolean stripComments)
Removes any comments from multiple line SQL using stripComments(String) and then extracts each individual statement using splitSQL(String).
static String[] splitSQL (String multiLineSQL)
Splits a (possible) multi-line SQL statement along ;'s and "go"'s.
static String stripComments (String multiLineSQL)
Searches through a String which contains SQL code and strips out any comments that are between \/**\/ or anything that matches SP--SP<text>
(to support the ANSI standard commenting of -- at the end of a line).
static String join (Collection< String > collection, String delimiter)
static List< String > splitAndTrim (String s, String regex)
Member Function Documentation
static String [] liquibase.util.StringUtils.processMutliLineSQL (String multiLineSQL, boolean stripComments) [static]
Removes any comments from multiple line SQL using stripComments(String) and then extracts each individual statement using splitSQL(String).
Parameters:
multiLineSQL A String containing all the SQL statements
stripComments If true then comments will be stripped, if false then they will be left in the code
Definition at line 37 of file StringUtils.java.
References liquibase.util.StringUtils.splitSQL(), and liquibase.util.StringUtils.stripComments().
{
        String stripped = stripComments ? stripComments(multiLineSQL) : multiLineSQL;
        return splitSQL(stripped);
    }
static String liquibase.util.StringUtils.stripComments (String multiLineSQL) [static]
Searches through a String which contains SQL code and strips out any comments that are between \/**\/ or anything that matches SP--SP<text>
(to support the ANSI standard commenting of -- at the end of a line).
Returns:
The String without the comments in
Definition at line 58 of file StringUtils.java.
Referenced by liquibase.util.StringUtils.processMutliLineSQL().
{
        String strippedSingleLines = multiLineSQL.replaceAll("\\s--\\s.*", "");
        return strippedSingleLines.replaceAll("/\\*[\n\\S\\s]*\\*/", "\n");
    }
The documentation for this class was generated from the following file:
java/liquibase/util/StringUtils.java