LiquiBase: liquibase.change.DropViewChange Class Reference
liquibase.change.DropViewChange
liquibase.change.DropViewChange Class Reference
Detailed Description
Drops an existing view.
Definition at line 19 of file DropViewChange.java.
Public Member Functions
DropViewChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getViewName ()
void setViewName (String viewName)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.DropViewChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 43 of file DropViewChange.java.
References liquibase.change.DropViewChange.getSchemaName(), and liquibase.change.DropViewChange.getViewName().
{
        return new SqlStatement[]{
                new DropViewStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getViewName()),
        };
    }
String liquibase.change.DropViewChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 49 of file DropViewChange.java.
References liquibase.change.DropViewChange.getViewName().
{
        return "View "+getViewName()+" dropped";
    }
Element liquibase.change.DropViewChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 53 of file DropViewChange.java.
References liquibase.change.DropViewChange.getSchemaName(), and liquibase.change.DropViewChange.getViewName().
{
        Element element = currentChangeLogFileDOM.createElement("dropView");
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("viewName", getViewName());
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DropViewChange.java