LiquiBase: liquibase.change.ModifyColumnChange Class Reference
liquibase.change.ModifyColumnChange
liquibase.change.ModifyColumnChange Class Reference
Detailed Description
Modifies the data type of an existing column.
Definition at line 23 of file ModifyColumnChange.java.
Public Member Functions
ModifyColumnChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
List< ColumnConfig > getColumns ()
void addColumn (ColumnConfig column)
void removeColumn (ColumnConfig column)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Member Function Documentation
SqlStatement [] liquibase.change.ModifyColumnChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 62 of file ModifyColumnChange.java.
References liquibase.change.ModifyColumnChange.getSchemaName(), and liquibase.change.ModifyColumnChange.getTableName().
{
        List<SqlStatement> sql = new ArrayList<SqlStatement>();
      for (ColumnConfig aColumn : columns) {
          String schemaName = getSchemaName() == null?database.getDefaultSchemaName():getSchemaName();
          if(database instanceof SybaseDatabase) {
                        sql.add(new RawSqlStatement("ALTER TABLE " + database.escapeTableName(schemaName, getTableName()) + " MODIFY " + aColumn.getName() + " " + aColumn.getType()));
        } else if (database instanceof MSSQLDatabase) {
                        sql.add(new RawSqlStatement("ALTER TABLE " + database.escapeTableName(schemaName, getTableName()) + " ALTER COLUMN " + aColumn.getName() + " " + aColumn.getType()));
        } else if (database instanceof MySQLDatabase) {
                        sql.add(new RawSqlStatement("ALTER TABLE " + database.escapeTableName(schemaName, getTableName()) + " MODIFY COLUMN " + aColumn.getName() + " " + aColumn.getType()));
        } else if (database instanceof OracleDatabase || database instanceof MaxDBDatabase) {
                        sql.add(new RawSqlStatement("ALTER TABLE " + database.escapeTableName(schemaName, getTableName()) + " MODIFY (" + aColumn.getName() + " " + aColumn.getType() + ")"));
        } else if (database instanceof DerbyDatabase) {
                        sql.add(new RawSqlStatement("ALTER TABLE " + database.escapeTableName(schemaName, getTableName()) + " ALTER COLUMN "+aColumn.getName()+" SET DATA TYPE " + aColumn.getType()));
        } else if (database instanceof HsqlDatabase) {
                        sql.add(new RawSqlStatement("ALTER TABLE " + database.escapeTableName(schemaName, getTableName()) + " ALTER COLUMN "+aColumn.getName()+" "+aColumn.getType()));
        } else if (database instanceof CacheDatabase) {
                        sql.add(new RawSqlStatement("ALTER TABLE " + database.escapeTableName(schemaName, getTableName()) + " ALTER COLUMN " + aColumn.getName() + " " + aColumn.getType()));
        } else if (database instanceof DB2Database) {
                        sql.add(new RawSqlStatement("ALTER TABLE " + database.escapeTableName(schemaName, getTableName()) + " ALTER COLUMN " + aColumn.getName() + " SET DATA TYPE " + aColumn.getType()));
                        sql.add(new ReorganizeTableStatement(schemaName, getTableName()));
        } else {
                        sql.add(new RawSqlStatement("ALTER TABLE " + database.escapeTableName(schemaName, getTableName()) + " ALTER COLUMN " + aColumn.getName() + " TYPE " + aColumn.getType()));
        }
      }
      return sql.toArray(new SqlStatement[sql.size()]);
    }
String liquibase.change.ModifyColumnChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 93 of file ModifyColumnChange.java.
References liquibase.change.ModifyColumnChange.getTableName().
{
                List<String> names = new ArrayList<String>(columns.size());
                for (ColumnConfig col : columns) {
                names.add(col.getName() + "(" + col.getType() + ")");
                }
        return "Columns " + StringUtils.join(names, ",") + " of " + getTableName() + " modified";
    }
Element liquibase.change.ModifyColumnChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 102 of file ModifyColumnChange.java.
References liquibase.change.ModifyColumnChange.getColumns(), liquibase.change.ModifyColumnChange.getSchemaName(), and liquibase.change.ModifyColumnChange.getTableName().
{
        Element node = currentChangeLogFileDOM.createElement("modifyColumn");
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        for (ColumnConfig col : getColumns()) {
          Element subNode = col.createNode(currentChangeLogFileDOM);
          node.appendChild(subNode);
        }
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/ModifyColumnChange.java