LiquiBase: liquibase.change.RenameColumnChange Class Reference
liquibase.change.RenameColumnChange
liquibase.change.RenameColumnChange Class Reference
Detailed Description
Renames an existing column.
Definition at line 20 of file RenameColumnChange.java.
Public Member Functions
RenameColumnChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getOldColumnName ()
void setOldColumnName (String oldColumnName)
String getNewColumnName ()
void setNewColumnName (String newColumnName)
String getColumnDataType ()
void setColumnDataType (String columnDataType)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.RenameColumnChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 73 of file RenameColumnChange.java.
References liquibase.change.RenameColumnChange.getColumnDataType(), liquibase.change.RenameColumnChange.getNewColumnName(), liquibase.change.RenameColumnChange.getOldColumnName(), liquibase.change.RenameColumnChange.getSchemaName(), and liquibase.change.RenameColumnChange.getTableName().
{
        return new SqlStatement[] {
                new RenameColumnStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName(), getOldColumnName(), getNewColumnName(), getColumnDataType())
        };
    }
String liquibase.change.RenameColumnChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 92 of file RenameColumnChange.java.
{
        return "Column "+tableName+"."+ oldColumnName + " renamed to " + newColumnName;
    }
Element liquibase.change.RenameColumnChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 96 of file RenameColumnChange.java.
References liquibase.change.RenameColumnChange.getNewColumnName(), liquibase.change.RenameColumnChange.getOldColumnName(), liquibase.change.RenameColumnChange.getSchemaName(), and liquibase.change.RenameColumnChange.getTableName().
{
        Element node = currentChangeLogFileDOM.createElement("renameColumn");
        if (getSchemaName() != null) {
            node.setAttribute("schemaName", getSchemaName());
        }
        node.setAttribute("tableName", getTableName());
        node.setAttribute("oldColumnName", getOldColumnName());
        node.setAttribute("newColumnName", getNewColumnName());
        return node;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/RenameColumnChange.java