LiquiBase: liquibase.change.DropNotNullConstraintChange Class Reference
liquibase.change.DropNotNullConstraintChange
liquibase.change.DropNotNullConstraintChange Class Reference
Detailed Description
Drops a not-null constraint from an existing column.
Definition at line 20 of file DropNotNullConstraintChange.java.
Public Member Functions
DropNotNullConstraintChange ()
String getSchemaName ()
void setSchemaName (String schemaName)
String getTableName ()
void setTableName (String tableName)
String getColumnName ()
void setColumnName (String columnName)
String getColumnDataType ()
void setColumnDataType (String columnDataType)
SqlStatement[] generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
String getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Element createNode (Document currentChangeLogFileDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Set< DatabaseObject > getAffectedDatabaseObjects ()
Protected Member Functions
Change[] createInverses ()
Member Function Documentation
SqlStatement [] liquibase.change.DropNotNullConstraintChange.generateStatements (Database database) throws UnsupportedChangeException
Generates the SQL statements required to run the change.
Parameters:
database databasethe target Database associated to this change's statements
Returns:
an array of Strings with the statements
Exceptions:
UnsupportedChangeException if this change is not supported by the Database passed as argument
Implements liquibase.change.Change.
Definition at line 64 of file DropNotNullConstraintChange.java.
References liquibase.change.DropNotNullConstraintChange.getColumnDataType(), liquibase.change.DropNotNullConstraintChange.getColumnName(), liquibase.change.DropNotNullConstraintChange.getSchemaName(), and liquibase.change.DropNotNullConstraintChange.getTableName().
{
        return new SqlStatement[]{new SetNullableStatement(getSchemaName() == null?database.getDefaultSchemaName():getSchemaName(), getTableName(), getColumnName(), getColumnDataType(), true)};
    }
String liquibase.change.DropNotNullConstraintChange.getConfirmationMessage ()
Confirmation message to be displayed after the change is executed.
Returns:
a String containing the message after the change is executed
Implements liquibase.change.Change.
Definition at line 80 of file DropNotNullConstraintChange.java.
References liquibase.change.DropNotNullConstraintChange.getColumnName(), and liquibase.change.DropNotNullConstraintChange.getTableName().
{
        return "Null constraint dropped from " + getTableName() + "." + getColumnName();
    }
Element liquibase.change.DropNotNullConstraintChange.createNode (Document currentChangeLogDOM)
Creates an XML element (of type Element) of the change object, and adds it to the Document object passed as argument.
Parameters:
currentChangeLogDOM the current Document where this element is being added
Returns:
the Element object created
Implements liquibase.change.Change.
Definition at line 84 of file DropNotNullConstraintChange.java.
References liquibase.change.DropNotNullConstraintChange.getColumnName(), liquibase.change.DropNotNullConstraintChange.getSchemaName(), and liquibase.change.DropNotNullConstraintChange.getTableName().
{
        Element element = currentChangeLogFileDOM.createElement("dropNotNullConstraint");
        if (getSchemaName() != null) {
            element.setAttribute("schemaName", getSchemaName());
        }
        element.setAttribute("tableName", getTableName());
        element.setAttribute("columnName", getColumnName());
        return element;
    }
The documentation for this class was generated from the following file:
java/liquibase/change/DropNotNullConstraintChange.java