LiquiBase: liquibase.database.Database Interface Reference
liquibase.database.Database
liquibase.database.Database Interface Reference
Detailed Description
Definition at line 17 of file Database.java.
Public Member Functions
String getDefaultDriver (String url)
If this database understands the given url, return the default driver class name.
boolean getAutoCommitMode ()
Auto-commit mode to run in.
boolean supportsDDLInTransaction ()
Determines if the database supports DDL within a transaction or not.
String getProductName ()
Returns the full database product name.
String getTypeName ()
Returns an all-lower-case short name of the product.
boolean supportsInitiallyDeferrableColumns ()
Returns whether this database support initially deferrable columns.
String getCurrentDateTimeFunction ()
Returns database-specific function for generating the current date/time.
String getConcatSql (String...values)
Returns SQL to concat the passed values.
String getBooleanType ()
Returns the actual database-specific data type to use a "boolean" column.
String getCurrencyType ()
Returns the actual database-specific data type to use a "currency" column.
String getUUIDType ()
Returns the actual database-specific data type to use a "UUID" column.
String getClobType ()
Returns the actual database-specific data type to use a "CLOB" column.
String getBlobType ()
Returns the actual database-specific data type to use a "BLOB" column.
String getDateTimeType ()
Returns the actual database-specific data type to use a "datetime" column.
String escapeTableName (String schemaName, String tableName)
Escapes the table name in a database-dependent manner so reserved words can be used as a table name (i.e.
Package Functions
boolean isCorrectDatabaseImplementation (Connection conn) throws JDBCException
Is this AbstractDatabase subclass the correct one to use for the given connection.
Member Function Documentation
String liquibase.database.Database.getDefaultDriver (String url)
If this database understands the given url, return the default driver class name.
Otherwise return null.
Implemented in liquibase.database.CacheDatabase, liquibase.database.DB2Database, liquibase.database.DerbyDatabase, liquibase.database.FirebirdDatabase, liquibase.database.H2Database, liquibase.database.HsqlDatabase, liquibase.database.MaxDBDatabase, liquibase.database.MSSQLDatabase, liquibase.database.MySQLDatabase, liquibase.database.OracleDatabase, liquibase.database.PostgresDatabase, liquibase.database.SybaseDatabase, and liquibase.database.UnsupportedDatabase.
boolean liquibase.database.Database.supportsDDLInTransaction ()
Determines if the database supports DDL within a transaction or not.
Returns:
True if the database supports DDL within a transaction, otherwise false.
Implemented in liquibase.database.AbstractDatabase, liquibase.database.FirebirdDatabase, and liquibase.database.SybaseDatabase.
String liquibase.database.Database.getProductName ()
Returns the full database product name.
May be different than what the JDBC connection reports (getDatabaseProductName())
Implemented in liquibase.database.CacheDatabase, liquibase.database.DB2Database, liquibase.database.DerbyDatabase, liquibase.database.FirebirdDatabase, liquibase.database.H2Database, liquibase.database.HsqlDatabase, liquibase.database.MaxDBDatabase, liquibase.database.MSSQLDatabase, liquibase.database.MySQLDatabase, liquibase.database.OracleDatabase, liquibase.database.PostgresDatabase, liquibase.database.SybaseDatabase, and liquibase.database.UnsupportedDatabase.
Referenced by liquibase.exception.StatementNotSupportedOnDatabaseException.StatementNotSupportedOnDatabaseException(), and liquibase.database.AbstractDatabase.toString().
String liquibase.database.Database.getTypeName ()
Returns an all-lower-case short name of the product.
Used for end-user selecting of database type such as the DBMS precondition.
Implemented in liquibase.database.CacheDatabase, liquibase.database.DB2Database, liquibase.database.DerbyDatabase, liquibase.database.FirebirdDatabase, liquibase.database.H2Database, liquibase.database.HsqlDatabase, liquibase.database.MaxDBDatabase, liquibase.database.MSSQLDatabase, liquibase.database.MySQLDatabase, liquibase.database.OracleDatabase, liquibase.database.PostgresDatabase, liquibase.database.SybaseDatabase, and liquibase.database.UnsupportedDatabase.
Referenced by liquibase.parser.filter.DbmsChangeSetFilter.DbmsChangeSetFilter().
String liquibase.database.Database.escapeTableName (String schemaName, String tableName)
Escapes the table name in a database-dependent manner so reserved words can be used as a table name (i.e.
"order"). Currently only escapes MS-SQL because other DBMSs store table names case-sensitively when escaping is used which could confuse end-users. Pass null to schemaName to use the default schema
Implemented in liquibase.database.AbstractDatabase, and liquibase.database.MSSQLDatabase.
Referenced by liquibase.database.sql.UpdateStatement.getSqlStatement(), liquibase.database.sql.DeleteStatement.getSqlStatement(), liquibase.database.sql.CreateTableStatement.getSqlStatement(), liquibase.database.sql.AddDefaultValueStatement.getSqlStatement(), and liquibase.lock.LockHandler.listLocks().
The documentation for this interface was generated from the following file:
java/liquibase/database/Database.java